//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web;
using System.Web.Services;

using FChoice.Toolkits.Clarify;
using FChoice.WebServices.Clarify;

namespace FChoice.WebServices.Clarify.Protocols.Logistics
{
	[Serializable]
	public class PartTransferResultProtocol
	{
		public PartTransferResultProtocol(){}
		
		internal PartTransferResultProtocol(FChoice.Toolkits.Clarify.Logistics.PartTransferResult result)
		{
			this.TransactionIDNum = result.TransactionIDNum;
			this.StandardCost = result.StandardCost;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.String TransactionIDNum;
		public System.Decimal StandardCost;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class CreatePartRequestDetailResultProtocol
	{
		public CreatePartRequestDetailResultProtocol(){}
		
		internal CreatePartRequestDetailResultProtocol(FChoice.Toolkits.Clarify.Logistics.CreatePartRequestDetailResult result)
		{
			this.DetailNumber = result.DetailNumber;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.String DetailNumber;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class GetLocationsServicingSiteResultProtocol
	{
		public GetLocationsServicingSiteResultProtocol(){}
		
		internal GetLocationsServicingSiteResultProtocol(FChoice.Toolkits.Clarify.Logistics.GetLocationsServicingSiteResult result)
		{
			this.InventoryLocationObjidList = result.InventoryLocationObjidList;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32[] InventoryLocationObjidList;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class GetAlternatePartsResultProtocol
	{
		public GetAlternatePartsResultProtocol(){}
		
		internal GetAlternatePartsResultProtocol(FChoice.Toolkits.Clarify.Logistics.GetAlternatePartsResult result)
		{
			this.AlternatePartList = result.AlternatePartList;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32[] AlternatePartList;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class PickResultProtocol
	{
		public PickResultProtocol(){}
		
		internal PickResultProtocol(FChoice.Toolkits.Clarify.Logistics.PickResult result)
		{
			this.TotalPicked = result.TotalPicked;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 TotalPicked;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
}
