//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web;
using System.Web.Services;

using FChoice.Toolkits.Clarify;
using FChoice.WebServices.Clarify;

namespace FChoice.WebServices.Clarify.Protocols.Logistics
{
	[Serializable]
	public class OpenContainerSetupProtocol
	{
		public OpenContainerSetupProtocol(){}

		public System.String ContainerName;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class SealContainerSetupProtocol
	{
		public SealContainerSetupProtocol(){}

		public System.String ContainerName;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateSubContainerSetupProtocol
	{
		public CreateSubContainerSetupProtocol(){}

		public System.String ContainerName;
		public System.String ParentContainerName;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateContainerSetupProtocol
	{
		public CreateContainerSetupProtocol(){}

		public System.String ContainerName;
		public System.String LocationName;
		public System.String BinName;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdatePartRequestDetailSetupProtocol
	{
		public UpdatePartRequestDetailSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.String PartNumber;
		public System.String PartDomain;
		public System.String PartRevision;
		public System.String SerialNumber;
		public System.Int32 Quantity;
		public System.Int32 SitePartObjid;
		public System.String DetailType;
		public System.String Priority;
		public System.String ShippingMethod;
		public System.String CarrierName;
		public System.Boolean HasWarranty;
		public System.String Notes;
		public System.String Status;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdatePartRequestHeaderSetupProtocol
	{
		public UpdatePartRequestHeaderSetupProtocol(){}

		public System.String PartRequestHeaderIDNum;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String ShipToSiteIDNum;
		public System.String BillSiteIDNum;
		public System.String CaseIDNum;
		public System.String PaymentMethod;
		public System.String PaymentTerms;
		public System.String Priority;
		public System.String Notes;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreatePartRequestHeaderSetupProtocol
	{
		public CreatePartRequestHeaderSetupProtocol(){}

		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String ShipToSiteIDNum;
		public System.String BillSiteIDNum;
		public System.String CaseIDNum;
		public System.String PaymentMethod;
		public System.String PaymentTerms;
		public System.String Priority;
		public System.String UserName;
		public System.String Notes;
		public System.DateTime CreateDate;
		public System.Int32 ContractObjid;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreatePartRequestHeaderSubcaseSetupProtocol
	{
		public CreatePartRequestHeaderSubcaseSetupProtocol(){}

		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String ShipToSiteIDNum;
		public System.String BillSiteIDNum;
		public System.String CaseIDNum;
		public System.String PaymentMethod;
		public System.String PaymentTerms;
		public System.String Priority;
		public System.String UserName;
		public System.String Notes;
		public System.DateTime CreateDate;
		public System.Int32 ContractObjid;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreatePartRequestHeaderCaseSetupProtocol
	{
		public CreatePartRequestHeaderCaseSetupProtocol(){}

		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String ShipToSiteIDNum;
		public System.String BillSiteIDNum;
		public System.String CaseIDNum;
		public System.String PaymentMethod;
		public System.String PaymentTerms;
		public System.String Priority;
		public System.String UserName;
		public System.String Notes;
		public System.DateTime CreateDate;
		public System.Int32 ContractObjid;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class PartTransferSetupProtocol
	{
		public PartTransferSetupProtocol(){}

		public System.String PartNumber;
		public System.String PartRevision;
		public System.String PartDomain;
		public System.Int32 Quantity;
		public System.String SerialNumber;
		public System.Boolean FromGood;
		public System.Boolean ToGood;
		public System.String UserName;
		public System.DateTime TransferDate;
		public System.String ReferenceIDNum;
		public System.String Notes;
		public System.Boolean GenerateTimeBombs;
		public Protocols.LocationProtocol ToLocation;
		public Protocols.LocationProtocol FromLocation;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreatePartRequestDetailSetupProtocol
	{
		public CreatePartRequestDetailSetupProtocol(){}

		public System.String PartRequestHeaderIDNum;
		public System.String Queue;
		public System.String PartNumber;
		public System.String PartDomain;
		public System.String PartRevision;
		public System.String SerialNumber;
		public System.Int32 Quantity;
		public System.Int32 SitePartObjid;
		public System.String DetailType;
		public System.String Priority;
		public System.String ShippingMethod;
		public System.String CarrierName;
		public System.String UserName;
		public System.Boolean HasWarranty;
		public System.String Notes;
		public System.String Status;
		public System.DateTime CreateDate;
		public System.DateTime DueDate;
		public System.Boolean GenerateTimeBombs;
		public System.Int32 ContractItemObjid;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdatePartStockingLevelSetupProtocol
	{
		public UpdatePartStockingLevelSetupProtocol(){}

		public System.String ToBinName;
		public System.String Queue;
		public System.String ToQueue;
		public System.String PartNumber;
		public System.String PartRevision;
		public System.String PartDomain;
		public System.Int16 PartMinimum;
		public System.Int16 PartMaximum;
		public System.Int16 PartReorderLevel;
		public System.Int16 PartReorderQuantity;
		public System.Boolean IsActive;
		public Protocols.LocationProtocol CurrentLocation;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class SetPartStockingLevelSetupProtocol
	{
		public SetPartStockingLevelSetupProtocol(){}

		public System.String Queue;
		public System.String PartNumber;
		public System.String PartRevision;
		public System.String PartDomain;
		public System.Int16 PartMinimum;
		public System.Int16 PartMaximum;
		public System.Int16 PartReorderLevel;
		public System.Int16 PartReorderQuantity;
		public System.Boolean IsActive;
		public Protocols.LocationProtocol Location;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateLocationServicingSiteSetupProtocol
	{
		public UpdateLocationServicingSiteSetupProtocol(){}

		public System.String SiteIDNum;
		public System.String LocationName;
		public System.Int16 LocationRank;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DeleteLocationServicingSiteSetupProtocol
	{
		public DeleteLocationServicingSiteSetupProtocol(){}

		public System.String SiteIDNum;
		public System.String LocationName;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddLocationServicingSiteSetupProtocol
	{
		public AddLocationServicingSiteSetupProtocol(){}

		public System.String SiteIDNum;
		public System.String LocationName;
		public System.Boolean IsActive;
		public System.Int16 LocationRank;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateInventoryLocationSetupProtocol
	{
		public UpdateInventoryLocationSetupProtocol(){}

		public System.String CurrentName;
		public System.String NewName;
		public System.String AccountType;
		public System.String Description;
		public System.String ReportsToLocation;
		public System.String CapitalGLAccount;
		public System.Boolean IsActive;
		public System.Boolean IsCompany;
		public System.String SiteIDNum;
		public FChoice.Toolkits.Clarify.PartAuthorizationLevel PartAuthorizationLevel;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddInventoryLocationSetupProtocol
	{
		public AddInventoryLocationSetupProtocol(){}

		public System.String LocationName;
		public System.String AccountType;
		public System.String Description;
		public System.String ReportsToLocation;
		public System.String CapitalGLAccount;
		public System.Boolean IsActive;
		public System.Boolean IsCompany;
		public System.String SiteIDNum;
		public FChoice.Toolkits.Clarify.PartAuthorizationLevel PartAuthorizationLevel;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateGLAccountSetupProtocol
	{
		public UpdateGLAccountSetupProtocol(){}

		public System.String CurrentName;
		public System.String NewName;
		public System.String AccountType;
		public System.String Description;
		public System.String AccountNumber;
		public System.Boolean IsExpenseGLAccount;
		public System.Boolean IsActive;
		public System.Boolean IsCompany;
		public System.String SiteIDNum;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddGLAccountSetupProtocol
	{
		public AddGLAccountSetupProtocol(){}

		public System.String AccountName;
		public System.String AccountType;
		public System.String Description;
		public System.String AccountNumber;
		public System.Boolean IsExpenseGLAccount;
		public System.Boolean IsActive;
		public System.Boolean IsCompany;
		public System.String SiteIDNum;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateInventoryBinSetupProtocol
	{
		public UpdateInventoryBinSetupProtocol(){}

		public System.String NewBinName;
		public System.Boolean IsActive;
		public Protocols.LocationProtocol CurrentLocation;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddInventoryBinSetupProtocol
	{
		public AddInventoryBinSetupProtocol(){}

		public System.Boolean IsActive;
		public Protocols.LocationProtocol Location;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class YankPartRequestSetupProtocol
	{
		public YankPartRequestSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.String WipBin;
		public System.DateTime YankDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ShipSetupProtocol
	{
		public ShipSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.String SiteName;
		public System.String Address1;
		public System.String Address2;
		public System.String City;
		public System.String State;
		public System.String ZipCode;
		public System.String Country;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String WaybillName;
		public System.String PackingList;
		public System.Int32 PieceCount;
		public System.Double TotalWeight;
		public System.String Status;
		public System.DateTime ShipDate;
		public System.String UserName;
		public System.String CarrierName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ReopenPartRequestSetupProtocol
	{
		public ReopenPartRequestSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.String NewStatus;
		public System.String WipBin;
		public System.DateTime ReopenDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class RejectPartRequestSetupProtocol
	{
		public RejectPartRequestSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.DateTime RejectDate;
		public System.String WipBin;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class MovePartRequestSetupProtocol
	{
		public MovePartRequestSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.String NewWipBin;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class GetLocationsServicingSiteSetupProtocol
	{
		public GetLocationsServicingSiteSetupProtocol(){}

		public System.String SiteIDNum;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class GetAlternatePartsSetupProtocol
	{
		public GetAlternatePartsSetupProtocol(){}

		public System.String PartNumber;
		public System.String PartDomain;
		public System.String PartRevision;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DeleteAlternatePartSetupProtocol
	{
		public DeleteAlternatePartSetupProtocol(){}

		public System.String PartNumber;
		public System.String PartRevision;
		public System.String PartDomain;
		public System.String AlternatePartNumber;
		public System.String AlternatePartRevision;
		public System.String AlternatePartDomain;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddAlternatePartSetupProtocol
	{
		public AddAlternatePartSetupProtocol(){}

		public System.String PartNumber;
		public System.String PartRevision;
		public System.String PartDomain;
		public System.String AlternatePartNumber;
		public System.String AlternatePartRevision;
		public System.String AlternatePartDomain;
		public System.Boolean IsReciprocal;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ForwardPartRequestSetupProtocol
	{
		public ForwardPartRequestSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.String NewQueue;
		public System.DateTime ForwardDate;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DispatchPartRequestSetupProtocol
	{
		public DispatchPartRequestSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.String Queue;
		public System.DateTime DispatchDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ClosePartRequestSetupProtocol
	{
		public ClosePartRequestSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.String NewStatus;
		public System.DateTime CloseDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ChangePartRequestStatusSetupProtocol
	{
		public ChangePartRequestStatusSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.String NewStatus;
		public System.DateTime ChangeDate;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AssignPartRequestSetupProtocol
	{
		public AssignPartRequestSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.String NewUser;
		public System.String WipBin;
		public System.DateTime AssignDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AcceptPartRequestSetupProtocol
	{
		public AcceptPartRequestSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.DateTime AcceptDate;
		public System.String WipBin;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class PickSetupProtocol
	{
		public PickSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public Protocols.LocationProtocol[] Locations;
		public System.Boolean UseGood;
		public System.String UserName;
		public System.DateTime PickDate;
		public System.String NewStatus;
		public System.String[] SerialNumbers;
		public System.Boolean UseTransitions;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UnpickSetupProtocol
	{
		public UnpickSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.Boolean UseGood;
		public System.String UserName;
		public System.DateTime UnpickDate;
		public System.String[] SerialNumbers;
		public System.Boolean UseTransitions;
		public System.Boolean GenerateTimeBombs;
		public Protocols.LocationProtocol Location;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class BackorderPartRequestSetupProtocol
	{
		public BackorderPartRequestSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.Int32 Quantity;
		public System.Boolean FromGood;
		public System.Boolean ToGood;
		public System.String SerialNumber;
		public System.String NewStatus;
		public System.DateTime ExpectedDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public System.Boolean UseTransitions;
		public Protocols.LocationProtocol ToLocation;
		public Protocols.LocationProtocol FromLocation;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class FulfillPartRequestSetupProtocol
	{
		public FulfillPartRequestSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.Int32 Quantity;
		public System.Boolean FromGood;
		public System.Boolean ToGood;
		public System.String SerialNumber;
		public System.String NewStatus;
		public System.String UserName;
		public System.DateTime FulfillDate;
		public System.Boolean GenerateTimeBombs;
		public System.Boolean UseTransitions;
		public Protocols.LocationProtocol ToLocation;
		public Protocols.LocationProtocol FromLocation;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ReceivePartRequestSetupProtocol
	{
		public ReceivePartRequestSetupProtocol(){}

		public System.String PartRequestDetailIDNum;
		public System.Boolean FromGood;
		public System.Boolean ToGood;
		public System.Int32 Quantity;
		public System.String SerialNumber;
		public System.String Status;
		public System.String CarrierName;
		public System.String WaybillName;
		public System.Boolean PossibleDamage;
		public System.Boolean NotProperlyPacked;
		public System.Boolean RouteToTest;
		public System.String UserName;
		public System.DateTime ReceiveDate;
		public System.Boolean AutoClose;
		public System.Boolean UseTransitions;
		public System.Boolean GenerateTimeBombs;
		public Protocols.LocationProtocol ToLocation;
		public Protocols.LocationProtocol FromLocation;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class SetLogisticsTransitionSetupProtocol
	{
		public SetLogisticsTransitionSetupProtocol(){}

		public FChoice.Toolkits.Clarify.PartRequestType PartRequestType;
		public FChoice.Toolkits.Clarify.PartRequestCondition StartCondition;
		public FChoice.Toolkits.Clarify.PartRequestCondition EndCondition;
		public System.String[] PrivilegeClasses;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
}
