//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web;
using System.Web.Services;

using FChoice.Toolkits.Clarify;
using FChoice.WebServices.Clarify;

namespace FChoice.WebServices.Clarify.Protocols.Quality
{
	[Serializable]
	public class FixFailedSetupProtocol
	{
		public FixFailedSetupProtocol(){}

		public System.String CRIDNum;
		public System.String Status;
		public System.String Notes;
		public System.String TestCase;
		public System.String FixedInRelease;
		public System.String UserName;
		public System.DateTime FailedDate;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogCREmailSetupProtocol
	{
		public LogCREmailSetupProtocol(){}

		public System.String CRIDNum;
		public System.DateTime LogDate;
		public System.String Message;
		public System.String Recipient;
		public System.String CCList;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public System.Boolean SendEmail;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ReplicateCRSetupProtocol
	{
		public ReplicateCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.String UserName;
		public System.DateTime ReplicatedDate;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateCRSetupProtocol
	{
		public UpdateCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.String PartNumber;
		public System.String PartRevision;
		public System.String PartDomain;
		public System.String Title;
		public System.String CRType;
		public System.String Priority;
		public System.String Frequency;
		public System.String FoundOnCPU;
		public System.String OperatingSystem;
		public System.String Memory;
		public System.String CRClass;
		public System.String IntroductionPhase;
		public System.String TestClass;
		public System.String FixedIn;
		public System.String UserName;
		public System.DateTime UpdateDate;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class FixCRSetupProtocol
	{
		public FixCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.String Status;
		public System.String Notes;
		public System.String UserName;
		public System.DateTime FixDate;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DuplicateCRSetupProtocol
	{
		public DuplicateCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.String Status;
		public System.String MasterCRIDNum;
		public System.String UserName;
		public System.DateTime CloseDate;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddModuleToCRSetupProtocol
	{
		public AddModuleToCRSetupProtocol(){}

		public System.Int32 FixObjid;
		public System.String FileName;
		public System.String FileRevision;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ChangeCRStatusSetupProtocol
	{
		public ChangeCRStatusSetupProtocol(){}

		public System.String CRIDNum;
		public System.String NewStatus;
		public System.DateTime ChangeDate;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ReopenCRSetupProtocol
	{
		public ReopenCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.String Status;
		public System.String WipBin;
		public System.String UserName;
		public System.DateTime ReopenDate;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CloseCRSetupProtocol
	{
		public CloseCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.String Status;
		public System.String Notes;
		public System.String TestCase;
		public System.String FixedInRelease;
		public System.String UserName;
		public System.DateTime CloseDate;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CheckClearQualityTransitionSetupProtocol
	{
		public CheckClearQualityTransitionSetupProtocol(){}

		public System.String OldCondition;
		public System.String OldStatus;
		public System.String NewCondition;
		public System.String NewStatus;
		public System.String UserName;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogCRNoteSetupProtocol
	{
		public LogCRNoteSetupProtocol(){}

		public System.String CRIDNum;
		public System.String Notes;
		public System.String InternalUseOnlyNotes;
		public System.DateTime LogDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateCRSetupProtocol
	{
		public CreateCRSetupProtocol(){}

		public System.String PartNumber;
		public System.String PartRevision;
		public System.String PartDomain;
		public System.String Title;
		public System.String Status;
		public System.String Description;
		public System.String CRType;
		public System.String Priority;
		public System.String Frequency;
		public System.String FoundOnCPU;
		public System.String OperatingSystem;
		public System.String Memory;
		public System.String CRClass;
		public System.String IntroductionPhase;
		public System.String TestClass;
		public System.String FixedIn;
		public System.String VerificationTest;
		public System.String Queue;
		public System.String UserName;
		public System.DateTime CreateDate;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class YankCRSetupProtocol
	{
		public YankCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.String WipBin;
		public System.DateTime YankDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class MoveCRSetupProtocol
	{
		public MoveCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.String NewWipBin;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AssignCRSetupProtocol
	{
		public AssignCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.String NewUser;
		public System.String WipBin;
		public System.DateTime AssignDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ForwardCRSetupProtocol
	{
		public ForwardCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.String NewQueue;
		public System.DateTime ForwardDate;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class RejectCRSetupProtocol
	{
		public RejectCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.DateTime RejectDate;
		public System.String WipBin;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AcceptCRSetupProtocol
	{
		public AcceptCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.DateTime AcceptDate;
		public System.String WipBin;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DispatchCRSetupProtocol
	{
		public DispatchCRSetupProtocol(){}

		public System.String CRIDNum;
		public System.String Queue;
		public System.DateTime DispatchDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
}
