//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Web;
using System.Web.Services;
using Protocol = FChoice.WebServices.Clarify.Client.Protocols.LogisticsToolkitSrv;
using FChoice.WebServices.Clarify.Client;

namespace FChoice.WebServices.Clarify.Client.Logistics
{
	public class LogisticsToolkitWS
	{
		private Protocol.LogisticsToolkitSrv toolkitProtocol;
		
		public LogisticsToolkitWS(ClarifySessionWS session)
		{
			toolkitProtocol = new Protocol.LogisticsToolkitSrv();
			toolkitProtocol.Url = new Uri( session.BaseUri, "LogisticsToolkitSrv.asmx" ).ToString();
			toolkitProtocol.AuthenticationHeaderValue = new Protocol.AuthenticationHeader();
			
			toolkitProtocol.AuthenticationHeaderValue.SessionID = session.SessionToken;
		}
		
		public Protocol.ToolkitResultProtocol OpenContainer(String containerName)
		{
			return toolkitProtocol.OpenContainer( containerName );
		}
		
		public Protocol.ToolkitResultProtocol OpenContainer(OpenContainerSetupWS setupParam)
		{
			return toolkitProtocol.OpenContainer( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol SealContainer(String containerName)
		{
			return toolkitProtocol.SealContainer( containerName );
		}
		
		public Protocol.ToolkitResultProtocol SealContainer(SealContainerSetupWS setupParam)
		{
			return toolkitProtocol.SealContainer( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol CreateSubContainer(String containerName, String parentContainerName)
		{
			return toolkitProtocol.CreateSubContainer( containerName, parentContainerName );
		}
		
		public Protocol.ToolkitResultProtocol CreateSubContainer(CreateSubContainerSetupWS setupParam)
		{
			return toolkitProtocol.CreateSubContainer( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol CreateContainer(String containerName, String locationName)
		{
			return toolkitProtocol.CreateContainer( containerName, locationName );
		}
		
		public Protocol.ToolkitResultProtocol CreateContainer(CreateContainerSetupWS setupParam)
		{
			return toolkitProtocol.CreateContainer( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdatePartRequestDetail(String partRequestDetailIDNum)
		{
			return toolkitProtocol.UpdatePartRequestDetail( partRequestDetailIDNum );
		}
		
		public Protocol.ToolkitResultProtocol UpdatePartRequestDetail(UpdatePartRequestDetailSetupWS setupParam)
		{
			return toolkitProtocol.UpdatePartRequestDetail( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdatePartRequestHeader(String partRequestHeaderIDNum)
		{
			return toolkitProtocol.UpdatePartRequestHeader( partRequestHeaderIDNum );
		}
		
		public Protocol.ToolkitResultProtocol UpdatePartRequestHeader(UpdatePartRequestHeaderSetupWS setupParam)
		{
			return toolkitProtocol.UpdatePartRequestHeader( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol CreatePartRequestHeader(String contactFirstName, String contactLastName, String contactPhone, String shipToSiteIDNum)
		{
			return toolkitProtocol.CreatePartRequestHeader( contactFirstName, contactLastName, contactPhone, shipToSiteIDNum );
		}
		
		public Protocol.ToolkitResultProtocol CreatePartRequestHeader(CreatePartRequestHeaderSetupWS setupParam)
		{
			return toolkitProtocol.CreatePartRequestHeader( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol CreatePartRequestHeaderSubcase(String contactFirstName, String contactLastName, String contactPhone, String shipToSiteIDNum, String caseIDNum)
		{
			return toolkitProtocol.CreatePartRequestHeaderSubcase( contactFirstName, contactLastName, contactPhone, shipToSiteIDNum, caseIDNum );
		}
		
		public Protocol.ToolkitResultProtocol CreatePartRequestHeaderSubcase(CreatePartRequestHeaderSubcaseSetupWS setupParam)
		{
			return toolkitProtocol.CreatePartRequestHeaderSubcase( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol CreatePartRequestHeaderCase(String contactFirstName, String contactLastName, String contactPhone, String shipToSiteIDNum, String caseIDNum)
		{
			return toolkitProtocol.CreatePartRequestHeaderCase( contactFirstName, contactLastName, contactPhone, shipToSiteIDNum, caseIDNum );
		}
		
		public Protocol.ToolkitResultProtocol CreatePartRequestHeaderCase(CreatePartRequestHeaderCaseSetupWS setupParam)
		{
			return toolkitProtocol.CreatePartRequestHeaderCase( setupParam.ToProtocol() );
		}
		
		public Protocol.PartTransferResultProtocol PartTransfer(String partNumber, String partRevision, String partDomain, Int32 quantity, Protocol.LocationProtocol fromlocation, Protocol.LocationProtocol tolocation)
		{
			return toolkitProtocol.PartTransfer( partNumber, partRevision, partDomain, quantity, fromlocation, tolocation );
		}
		
		public Protocol.PartTransferResultProtocol PartTransfer(String partNumber, String partRevision, String partDomain, String serialNumber, Protocol.LocationProtocol fromlocation, Protocol.LocationProtocol tolocation)
		{
			return toolkitProtocol.PartTransfer( partNumber, partRevision, partDomain, serialNumber, fromlocation, tolocation );
		}
		
		public Protocol.PartTransferResultProtocol PartTransfer(PartTransferSetupWS setupParam)
		{
			return toolkitProtocol.PartTransfer( setupParam.ToProtocol() );
		}
		
		public Protocol.CreatePartRequestDetailResultProtocol CreatePartRequestDetail(String partRequestHeaderIDNum, String partNumber, String partDomain, String partRevision, Int32 quantity)
		{
			return toolkitProtocol.CreatePartRequestDetail( partRequestHeaderIDNum, partNumber, partDomain, partRevision, quantity );
		}
		
		public Protocol.CreatePartRequestDetailResultProtocol CreatePartRequestDetail(String partRequestHeaderIDNum, Int32 quantity, Int32 sitePartObjid)
		{
			return toolkitProtocol.CreatePartRequestDetail( partRequestHeaderIDNum, quantity, sitePartObjid );
		}
		
		public Protocol.CreatePartRequestDetailResultProtocol CreatePartRequestDetail(String partRequestHeaderIDNum, String partNumber, String partDomain, String partRevision, String serialNumber)
		{
			return toolkitProtocol.CreatePartRequestDetail( partRequestHeaderIDNum, partNumber, partDomain, partRevision, serialNumber );
		}
		
		public Protocol.CreatePartRequestDetailResultProtocol CreatePartRequestDetail(String partRequestHeaderIDNum, String serialNumber, Int32 sitePartObjid)
		{
			return toolkitProtocol.CreatePartRequestDetail( partRequestHeaderIDNum, serialNumber, sitePartObjid );
		}
		
		public Protocol.CreatePartRequestDetailResultProtocol CreatePartRequestDetail(CreatePartRequestDetailSetupWS setupParam)
		{
			return toolkitProtocol.CreatePartRequestDetail( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdatePartStockingLevel(Protocol.LocationProtocol currentLocation, String queue, String partNumber, String partRevision, String partDomain)
		{
			return toolkitProtocol.UpdatePartStockingLevel( currentLocation, queue, partNumber, partRevision, partDomain );
		}
		
		public Protocol.ToolkitResultProtocol UpdatePartStockingLevel(UpdatePartStockingLevelSetupWS setupParam)
		{
			return toolkitProtocol.UpdatePartStockingLevel( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol SetPartStockingLevel(Protocol.LocationProtocol location, String queue, String partNumber, String partRevision, String partDomain, Int16 partMinimum, Int16 partMaximum, Int16 partReorderLevel, Int16 partReorderQuantity)
		{
			return toolkitProtocol.SetPartStockingLevel( location, queue, partNumber, partRevision, partDomain, partMinimum, partMaximum, partReorderLevel, partReorderQuantity );
		}
		
		public Protocol.ToolkitResultProtocol SetPartStockingLevel(SetPartStockingLevelSetupWS setupParam)
		{
			return toolkitProtocol.SetPartStockingLevel( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateLocationServicingSite(String siteIDNum, String locationName, Int16 locationRank)
		{
			return toolkitProtocol.UpdateLocationServicingSite( siteIDNum, locationName, locationRank );
		}
		
		public Protocol.ToolkitResultProtocol UpdateLocationServicingSite(UpdateLocationServicingSiteSetupWS setupParam)
		{
			return toolkitProtocol.UpdateLocationServicingSite( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DeleteLocationServicingSite(String siteIDNum, String locationName)
		{
			return toolkitProtocol.DeleteLocationServicingSite( siteIDNum, locationName );
		}
		
		public Protocol.ToolkitResultProtocol DeleteLocationServicingSite(DeleteLocationServicingSiteSetupWS setupParam)
		{
			return toolkitProtocol.DeleteLocationServicingSite( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol AddLocationServicingSite(String siteIDNum, String locationName, Int16 locationRank)
		{
			return toolkitProtocol.AddLocationServicingSite( siteIDNum, locationName, locationRank );
		}
		
		public Protocol.ToolkitResultProtocol AddLocationServicingSite(AddLocationServicingSiteSetupWS setupParam)
		{
			return toolkitProtocol.AddLocationServicingSite( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateInventoryLocation(String currentName)
		{
			return toolkitProtocol.UpdateInventoryLocation( currentName );
		}
		
		public Protocol.ToolkitResultProtocol UpdateInventoryLocation(UpdateInventoryLocationSetupWS setupParam)
		{
			return toolkitProtocol.UpdateInventoryLocation( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol AddInventoryLocation(String locationName, String capitalGLAccount, String siteIDNum, Protocol.PartAuthorizationLevel partAuthorizationLevel)
		{
			return toolkitProtocol.AddInventoryLocation( locationName, capitalGLAccount, siteIDNum, partAuthorizationLevel );
		}
		
		public Protocol.ToolkitResultProtocol AddInventoryLocation(AddInventoryLocationSetupWS setupParam)
		{
			return toolkitProtocol.AddInventoryLocation( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateGLAccount(String currentName, String siteIDNum)
		{
			return toolkitProtocol.UpdateGLAccount( currentName, siteIDNum );
		}
		
		public Protocol.ToolkitResultProtocol UpdateGLAccount(UpdateGLAccountSetupWS setupParam)
		{
			return toolkitProtocol.UpdateGLAccount( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol AddGLAccount(String accountName, String siteIDNum)
		{
			return toolkitProtocol.AddGLAccount( accountName, siteIDNum );
		}
		
		public Protocol.ToolkitResultProtocol AddGLAccount(AddGLAccountSetupWS setupParam)
		{
			return toolkitProtocol.AddGLAccount( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateInventoryBin(Protocol.LocationProtocol currentLocation, String newBinName)
		{
			return toolkitProtocol.UpdateInventoryBin( currentLocation, newBinName );
		}
		
		public Protocol.ToolkitResultProtocol UpdateInventoryBin(UpdateInventoryBinSetupWS setupParam)
		{
			return toolkitProtocol.UpdateInventoryBin( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol AddInventoryBin(Protocol.LocationProtocol location)
		{
			return toolkitProtocol.AddInventoryBin( location );
		}
		
		public Protocol.ToolkitResultProtocol AddInventoryBin(AddInventoryBinSetupWS setupParam)
		{
			return toolkitProtocol.AddInventoryBin( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol YankPartRequest(String partRequestDetailIDNum)
		{
			return toolkitProtocol.YankPartRequest( partRequestDetailIDNum );
		}
		
		public Protocol.ToolkitResultProtocol YankPartRequest(YankPartRequestSetupWS setupParam)
		{
			return toolkitProtocol.YankPartRequest( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol Ship(String partRequestDetailIDNum)
		{
			return toolkitProtocol.Ship( partRequestDetailIDNum );
		}
		
		public Protocol.ToolkitResultProtocol Ship(ShipSetupWS setupParam)
		{
			return toolkitProtocol.Ship( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol ReopenPartRequest(String partRequestDetailIDNum)
		{
			return toolkitProtocol.ReopenPartRequest( partRequestDetailIDNum );
		}
		
		public Protocol.ToolkitResultProtocol ReopenPartRequest(ReopenPartRequestSetupWS setupParam)
		{
			return toolkitProtocol.ReopenPartRequest( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol RejectPartRequest(String partRequestDetailIDNum)
		{
			return toolkitProtocol.RejectPartRequest( partRequestDetailIDNum );
		}
		
		public Protocol.ToolkitResultProtocol RejectPartRequest(RejectPartRequestSetupWS setupParam)
		{
			return toolkitProtocol.RejectPartRequest( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol MovePartRequest(String partRequestDetailIDNum, String newWipBin)
		{
			return toolkitProtocol.MovePartRequest( partRequestDetailIDNum, newWipBin );
		}
		
		public Protocol.ToolkitResultProtocol MovePartRequest(MovePartRequestSetupWS setupParam)
		{
			return toolkitProtocol.MovePartRequest( setupParam.ToProtocol() );
		}
		
		public Protocol.GetLocationsServicingSiteResultProtocol GetLocationsServicingSite(String siteIDNum)
		{
			return toolkitProtocol.GetLocationsServicingSite( siteIDNum );
		}
		
		public Protocol.GetLocationsServicingSiteResultProtocol GetLocationsServicingSite(GetLocationsServicingSiteSetupWS setupParam)
		{
			return toolkitProtocol.GetLocationsServicingSite( setupParam.ToProtocol() );
		}
		
		public Protocol.GetAlternatePartsResultProtocol GetAlternateParts(String partNumber, String partDomain, String partRevision)
		{
			return toolkitProtocol.GetAlternateParts( partNumber, partDomain, partRevision );
		}
		
		public Protocol.GetAlternatePartsResultProtocol GetAlternateParts(GetAlternatePartsSetupWS setupParam)
		{
			return toolkitProtocol.GetAlternateParts( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DeleteAlternatePart(String partNumber, String partRevision, String partDomain, String alternatePartNumber, String alternatePartRevision, String alternatePartDomain)
		{
			return toolkitProtocol.DeleteAlternatePart( partNumber, partRevision, partDomain, alternatePartNumber, alternatePartRevision, alternatePartDomain );
		}
		
		public Protocol.ToolkitResultProtocol DeleteAlternatePart(DeleteAlternatePartSetupWS setupParam)
		{
			return toolkitProtocol.DeleteAlternatePart( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol AddAlternatePart(String partNumber, String partRevision, String partDomain, String alternatePartNumber, String alternatePartRevision, String alternatePartDomain)
		{
			return toolkitProtocol.AddAlternatePart( partNumber, partRevision, partDomain, alternatePartNumber, alternatePartRevision, alternatePartDomain );
		}
		
		public Protocol.ToolkitResultProtocol AddAlternatePart(AddAlternatePartSetupWS setupParam)
		{
			return toolkitProtocol.AddAlternatePart( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol ForwardPartRequest(String partRequestDetailIDNum, String newQueue)
		{
			return toolkitProtocol.ForwardPartRequest( partRequestDetailIDNum, newQueue );
		}
		
		public Protocol.ToolkitResultProtocol ForwardPartRequest(ForwardPartRequestSetupWS setupParam)
		{
			return toolkitProtocol.ForwardPartRequest( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DispatchPartRequest(String partRequestDetailIDNum, String queue)
		{
			return toolkitProtocol.DispatchPartRequest( partRequestDetailIDNum, queue );
		}
		
		public Protocol.ToolkitResultProtocol DispatchPartRequest(DispatchPartRequestSetupWS setupParam)
		{
			return toolkitProtocol.DispatchPartRequest( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol ClosePartRequest(String partRequestDetailIDNum)
		{
			return toolkitProtocol.ClosePartRequest( partRequestDetailIDNum );
		}
		
		public Protocol.ToolkitResultProtocol ClosePartRequest(ClosePartRequestSetupWS setupParam)
		{
			return toolkitProtocol.ClosePartRequest( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol ChangePartRequestStatus(String partRequestDetailIDNum)
		{
			return toolkitProtocol.ChangePartRequestStatus( partRequestDetailIDNum );
		}
		
		public Protocol.ToolkitResultProtocol ChangePartRequestStatus(ChangePartRequestStatusSetupWS setupParam)
		{
			return toolkitProtocol.ChangePartRequestStatus( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol AssignPartRequest(String partRequestDetailIDNum)
		{
			return toolkitProtocol.AssignPartRequest( partRequestDetailIDNum );
		}
		
		public Protocol.ToolkitResultProtocol AssignPartRequest(AssignPartRequestSetupWS setupParam)
		{
			return toolkitProtocol.AssignPartRequest( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol AcceptPartRequest(String partRequestDetailIDNum)
		{
			return toolkitProtocol.AcceptPartRequest( partRequestDetailIDNum );
		}
		
		public Protocol.ToolkitResultProtocol AcceptPartRequest(AcceptPartRequestSetupWS setupParam)
		{
			return toolkitProtocol.AcceptPartRequest( setupParam.ToProtocol() );
		}
		
		public Protocol.PickResultProtocol Pick(String partRequestDetailIDNum)
		{
			return toolkitProtocol.Pick( partRequestDetailIDNum );
		}
		
		public Protocol.PickResultProtocol Pick(String partRequestDetailIDNum, String[] serialNumbers)
		{
			return toolkitProtocol.Pick( partRequestDetailIDNum, serialNumbers );
		}
		
		public Protocol.PickResultProtocol Pick(String partRequestDetailIDNum, Boolean useTransitions)
		{
			return toolkitProtocol.Pick( partRequestDetailIDNum, useTransitions );
		}
		
		public Protocol.PickResultProtocol Pick(String partRequestDetailIDNum, Boolean useTransitions, String[] serialNumbers)
		{
			return toolkitProtocol.Pick( partRequestDetailIDNum, useTransitions, serialNumbers );
		}
		
		public Protocol.PickResultProtocol Pick(PickSetupWS setupParam)
		{
			return toolkitProtocol.Pick( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol Unpick(String partRequestDetailIDNum, Protocol.LocationProtocol location)
		{
			return toolkitProtocol.Unpick( partRequestDetailIDNum, location );
		}
		
		public Protocol.ToolkitResultProtocol Unpick(String partRequestDetailIDNum, Protocol.LocationProtocol location, String[] serialNumbers)
		{
			return toolkitProtocol.Unpick( partRequestDetailIDNum, location, serialNumbers );
		}
		
		public Protocol.ToolkitResultProtocol Unpick(String partRequestDetailIDNum, Protocol.LocationProtocol location, Boolean useTransitions)
		{
			return toolkitProtocol.Unpick( partRequestDetailIDNum, location, useTransitions );
		}
		
		public Protocol.ToolkitResultProtocol Unpick(String partRequestDetailIDNum, Protocol.LocationProtocol location, Boolean useTransitions, String[] serialNumbers)
		{
			return toolkitProtocol.Unpick( partRequestDetailIDNum, location, useTransitions, serialNumbers );
		}
		
		public Protocol.ToolkitResultProtocol Unpick(UnpickSetupWS setupParam)
		{
			return toolkitProtocol.Unpick( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol BackorderPartRequest(String partRequestDetailIDNum, DateTime expectedDate, Int32 quantity)
		{
			return toolkitProtocol.BackorderPartRequest( partRequestDetailIDNum, expectedDate, quantity );
		}
		
		public Protocol.ToolkitResultProtocol BackorderPartRequest(String partRequestDetailIDNum, DateTime expectedDate, String serialNumber)
		{
			return toolkitProtocol.BackorderPartRequest( partRequestDetailIDNum, expectedDate, serialNumber );
		}
		
		public Protocol.ToolkitResultProtocol BackorderPartRequest(String partRequestDetailIDNum, DateTime expectedDate, Boolean useTransitions, Int32 quantity)
		{
			return toolkitProtocol.BackorderPartRequest( partRequestDetailIDNum, expectedDate, useTransitions, quantity );
		}
		
		public Protocol.ToolkitResultProtocol BackorderPartRequest(String partRequestDetailIDNum, DateTime expectedDate, Boolean useTransitions, String serialNumber)
		{
			return toolkitProtocol.BackorderPartRequest( partRequestDetailIDNum, expectedDate, useTransitions, serialNumber );
		}
		
		public Protocol.ToolkitResultProtocol BackorderPartRequest(BackorderPartRequestSetupWS setupParam)
		{
			return toolkitProtocol.BackorderPartRequest( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol FulfillPartRequest(String partRequestDetailIDNum, Int32 quantity)
		{
			return toolkitProtocol.FulfillPartRequest( partRequestDetailIDNum, quantity );
		}
		
		public Protocol.ToolkitResultProtocol FulfillPartRequest(String partRequestDetailIDNum, String serialNumber)
		{
			return toolkitProtocol.FulfillPartRequest( partRequestDetailIDNum, serialNumber );
		}
		
		public Protocol.ToolkitResultProtocol FulfillPartRequest(String partRequestDetailIDNum, Boolean useTransitions, Int32 quantity)
		{
			return toolkitProtocol.FulfillPartRequest( partRequestDetailIDNum, useTransitions, quantity );
		}
		
		public Protocol.ToolkitResultProtocol FulfillPartRequest(String partRequestDetailIDNum, Boolean useTransitions, String serialNumber)
		{
			return toolkitProtocol.FulfillPartRequest( partRequestDetailIDNum, useTransitions, serialNumber );
		}
		
		public Protocol.ToolkitResultProtocol FulfillPartRequest(FulfillPartRequestSetupWS setupParam)
		{
			return toolkitProtocol.FulfillPartRequest( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol ReceivePartRequest(String partRequestDetailIDNum, Int32 quantity, Protocol.LocationProtocol toLocation)
		{
			return toolkitProtocol.ReceivePartRequest( partRequestDetailIDNum, quantity, toLocation );
		}
		
		public Protocol.ToolkitResultProtocol ReceivePartRequest(String partRequestDetailIDNum, String serialNumber, Protocol.LocationProtocol toLocation)
		{
			return toolkitProtocol.ReceivePartRequest( partRequestDetailIDNum, serialNumber, toLocation );
		}
		
		public Protocol.ToolkitResultProtocol ReceivePartRequest(String partRequestDetailIDNum, Int32 quantity, Protocol.LocationProtocol toLocation, Boolean useTransitions)
		{
			return toolkitProtocol.ReceivePartRequest( partRequestDetailIDNum, quantity, toLocation, useTransitions );
		}
		
		public Protocol.ToolkitResultProtocol ReceivePartRequest(String partRequestDetailIDNum, String serialNumber, Protocol.LocationProtocol toLocation, Boolean useTransitions)
		{
			return toolkitProtocol.ReceivePartRequest( partRequestDetailIDNum, serialNumber, toLocation, useTransitions );
		}
		
		public Protocol.ToolkitResultProtocol ReceivePartRequest(ReceivePartRequestSetupWS setupParam)
		{
			return toolkitProtocol.ReceivePartRequest( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol SetLogisticsTransition(Protocol.PartRequestType partRequestType, Protocol.PartRequestCondition startCondition, Protocol.PartRequestCondition endCondition, String[] privilegeClasses)
		{
			return toolkitProtocol.SetLogisticsTransition( partRequestType, startCondition, endCondition, privilegeClasses );
		}
		
		public Protocol.ToolkitResultProtocol SetLogisticsTransition(SetLogisticsTransitionSetupWS setupParam)
		{
			return toolkitProtocol.SetLogisticsTransition( setupParam.ToProtocol() );
		}
		
	}
}
