//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web;
using System.Web.Services;

using FChoice.Toolkits.Clarify;
using FChoice.WebServices.Clarify;

namespace FChoice.WebServices.Clarify.Protocols.Support
{
	[Serializable]
	public class GetSubcaseTimeAndExpensesSetupProtocol
	{
		public GetSubcaseTimeAndExpensesSetupProtocol(){}

		public System.String SubcaseIDNum;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class GetCaseTimeAndExpensesSetupProtocol
	{
		public GetCaseTimeAndExpensesSetupProtocol(){}

		public System.String CaseIDNum;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogSubcaseEmailSetupProtocol
	{
		public LogSubcaseEmailSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String ActionType;
		public System.DateTime LogDate;
		public System.String Message;
		public System.String Recipient;
		public System.String CCList;
		public System.String UserName;
		public System.String NewStatus;
		public System.String CommitmentTitle;
		public System.String CommitmentNotes;
		public System.DateTime CommitmentDueDate;
		public System.Int32 CommitmentPriorWarning;
		public System.Boolean IsCommitmentToCustomer;
		public System.String CommitmentActionType;
		public System.Int32 CommitmentContactObjid;
		public System.Boolean GenerateTimeBombs;
		public System.Boolean SendEmail;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogCaseEmailSetupProtocol
	{
		public LogCaseEmailSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String ActionType;
		public System.DateTime LogDate;
		public System.String Message;
		public System.String Recipient;
		public System.String CCList;
		public System.String UserName;
		public System.String NewStatus;
		public System.String CommitmentTitle;
		public System.String CommitmentNotes;
		public System.DateTime CommitmentDueDate;
		public System.Int32 CommitmentPriorWarning;
		public System.Boolean IsCommitmentToCustomer;
		public System.String CommitmentActionType;
		public System.Int32 CommitmentContactObjid;
		public System.Boolean GenerateTimeBombs;
		public System.Boolean SendEmail;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UnrelateCaseFromParentCaseSetupProtocol
	{
		public UnrelateCaseFromParentCaseSetupProtocol(){}

		public System.String CaseIDNum;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class RelateCaseToParentCaseSetupProtocol
	{
		public RelateCaseToParentCaseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String ParentCaseIDNum;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogSubcaseNoteSetupProtocol
	{
		public LogSubcaseNoteSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String ActionType;
		public System.String Notes;
		public System.String InternalUseOnlyNotes;
		public System.DateTime LogDate;
		public System.String UserName;
		public System.String NewStatus;
		public System.String CommitmentTitle;
		public System.String CommitmentNotes;
		public System.DateTime CommitmentDueDate;
		public System.Int32 CommitmentPriorWarning;
		public System.Boolean IsCommitmentToCustomer;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogCaseNoteSetupProtocol
	{
		public LogCaseNoteSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String ActionType;
		public System.String Notes;
		public System.String InternalUseOnlyNotes;
		public System.DateTime LogDate;
		public System.String UserName;
		public System.String NewStatus;
		public System.String CommitmentTitle;
		public System.String CommitmentNotes;
		public System.DateTime CommitmentDueDate;
		public System.Int32 CommitmentPriorWarning;
		public System.Boolean IsCommitmentToCustomer;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogSubcaseResearchSetupProtocol
	{
		public LogSubcaseResearchSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String ActionType;
		public System.String Notes;
		public System.String InternalUseOnlyNotes;
		public System.DateTime LogDate;
		public System.Int32 ResearchDuration;
		public System.String UserName;
		public System.String NewStatus;
		public System.String CommitmentTitle;
		public System.String CommitmentNotes;
		public System.DateTime CommitmentDueDate;
		public System.Int32 CommitmentPriorWarning;
		public System.Boolean IsCommitmentToCustomer;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogCaseResearchSetupProtocol
	{
		public LogCaseResearchSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String ActionType;
		public System.String Notes;
		public System.String InternalUseOnlyNotes;
		public System.DateTime LogDate;
		public System.Int32 ResearchDuration;
		public System.String UserName;
		public System.String NewStatus;
		public System.String CommitmentTitle;
		public System.String CommitmentNotes;
		public System.DateTime CommitmentDueDate;
		public System.Int32 CommitmentPriorWarning;
		public System.Boolean IsCommitmentToCustomer;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogSubcasePhoneSetupProtocol
	{
		public LogSubcasePhoneSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String ActionType;
		public System.String Notes;
		public System.String InternalUseOnlyNotes;
		public System.DateTime LogDate;
		public System.DateTime LogEndDate;
		public System.String UserName;
		public System.String NewStatus;
		public System.String CommitmentTitle;
		public System.String CommitmentNotes;
		public System.DateTime CommitmentDueDate;
		public System.Int32 CommitmentPriorWarning;
		public System.Boolean IsCommitmentToCustomer;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogCasePhoneSetupProtocol
	{
		public LogCasePhoneSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String ActionType;
		public System.String Notes;
		public System.String InternalUseOnlyNotes;
		public System.DateTime LogDate;
		public System.DateTime LogEndDate;
		public System.String UserName;
		public System.String NewStatus;
		public System.String CommitmentTitle;
		public System.String CommitmentNotes;
		public System.DateTime CommitmentDueDate;
		public System.Int32 CommitmentPriorWarning;
		public System.Boolean IsCommitmentToCustomer;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ReopenSubcaseSetupProtocol
	{
		public ReopenSubcaseSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String WipBin;
		public System.String Status;
		public System.DateTime ReopenDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ReopenCaseSetupProtocol
	{
		public ReopenCaseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String WipBin;
		public System.String Status;
		public System.DateTime ReopenDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateSubcaseSetupProtocol
	{
		public UpdateSubcaseSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String Priority;
		public System.String Severity;
		public System.String UserName;
		public System.DateTime UpdateDate;
		public System.Boolean OnlyOwner;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateCaseSetupProtocol
	{
		public UpdateCaseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String Priority;
		public System.String Severity;
		public System.String CaseType;
		public System.String UserName;
		public System.DateTime UpdateDate;
		public System.Boolean OnlyOwner;
		public System.Boolean GenerateTimeBombs;
		public System.String Title;
		public System.Int32 PartRevisionObjid;
		public System.Int32 SitePartObjid;
		public System.Int32 ContractObjid;
		public System.Boolean ClearSitePartRelation;
		public System.Boolean ClearContractRelation;
		public System.Boolean ClearPartRevisionRelation;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AssignSubcaseSetupProtocol
	{
		public AssignSubcaseSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String NewUser;
		public System.String WipBin;
		public System.DateTime AssignDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AssignCaseSetupProtocol
	{
		public AssignCaseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String NewUser;
		public System.String WipBin;
		public System.DateTime AssignDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class RejectSubcaseSetupProtocol
	{
		public RejectSubcaseSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.DateTime RejectDate;
		public System.String WipBin;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class RejectCaseSetupProtocol
	{
		public RejectCaseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.DateTime RejectDate;
		public System.String WipBin;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AcceptSubcaseSetupProtocol
	{
		public AcceptSubcaseSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.DateTime AcceptDate;
		public System.String WipBin;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AcceptCaseSetupProtocol
	{
		public AcceptCaseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.DateTime AcceptDate;
		public System.String WipBin;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class MoveSubcaseSetupProtocol
	{
		public MoveSubcaseSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String NewWipBin;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class MoveCaseSetupProtocol
	{
		public MoveCaseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String NewWipBin;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class FulfillCommitmentSetupProtocol
	{
		public FulfillCommitmentSetupProtocol(){}

		public System.Int32 LogObjid;
		public System.DateTime FulfillDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateSubcaseCommitmentSetupProtocol
	{
		public UpdateSubcaseCommitmentSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String Title;
		public System.String ActionType;
		public System.DateTime CommitmentDate;
		public System.Int32 CommitmentObjid;
		public System.Int32 PriorWarning;
		public System.Boolean IsMadeToCustomer;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String Notes;
		public System.DateTime UpdateDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateCaseCommitmentSetupProtocol
	{
		public UpdateCaseCommitmentSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String Title;
		public System.String ActionType;
		public System.DateTime CommitmentDate;
		public System.Int32 CommitmentObjid;
		public System.Int32 PriorWarning;
		public System.Boolean IsMadeToCustomer;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String Notes;
		public System.DateTime UpdateDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogSubcaseCommitmentSetupProtocol
	{
		public LogSubcaseCommitmentSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String Title;
		public System.String ActionType;
		public System.DateTime LogDate;
		public System.DateTime CommitmentDate;
		public System.Int32 PriorWarning;
		public System.Boolean IsMadeToCustomer;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public System.Boolean GenerateCommitmentEmail;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogCaseCommitmentSetupProtocol
	{
		public LogCaseCommitmentSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String Title;
		public System.String ActionType;
		public System.DateTime LogDate;
		public System.DateTime CommitmentDate;
		public System.Int32 PriorWarning;
		public System.Boolean IsMadeToCustomer;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public System.Boolean GenerateCommitmentEmail;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class YankSubcaseSetupProtocol
	{
		public YankSubcaseSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String WipBin;
		public System.DateTime YankDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class YankCaseSetupProtocol
	{
		public YankCaseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String WipBin;
		public System.DateTime YankDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class InitialResponseSetupProtocol
	{
		public InitialResponseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.DateTime ResponseDate;
		public System.String UserName;
		public System.Boolean IsVIAPhone;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ForwardSubcaseSetupProtocol
	{
		public ForwardSubcaseSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String NewQueue;
		public System.DateTime ForwardDate;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ForwardCaseSetupProtocol
	{
		public ForwardCaseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String NewQueue;
		public System.DateTime ForwardDate;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DispatchSubcaseSetupProtocol
	{
		public DispatchSubcaseSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String Queue;
		public System.DateTime DispatchDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DispatchCaseSetupProtocol
	{
		public DispatchCaseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String Queue;
		public System.DateTime DispatchDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateSubcaseSetupProtocol
	{
		public CreateSubcaseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String Title;
		public System.Boolean IsGeneral;
		public System.String Priority;
		public System.String Severity;
		public System.String Status;
		public System.String Notes;
		public System.String Queue;
		public System.DateTime CreateDate;
		public System.DateTime DueDate;
		public System.Int32 PriorWarning;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateCaseSetupProtocol
	{
		public CreateCaseSetupProtocol(){}

		public System.String SiteIDNum;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String PartNumber;
		public System.String PartRevision;
		public System.String PartDomain;
		public System.String SerialNumber;
		public System.Int32 SitePartObjid;
		public System.String ContractIDNum;
		public System.String Title;
		public System.String CaseType;
		public System.String Priority;
		public System.String Severity;
		public System.String Status;
		public System.String PhoneLogNotes;
		public System.String Queue;
		public System.DateTime CreateDate;
		public System.DateTime PhoneEndDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateCaseObjidSetupProtocol
	{
		public CreateCaseObjidSetupProtocol(){}

		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.Int32 SitePartObjid;
		public System.String Title;
		public System.String CaseType;
		public System.String Priority;
		public System.String Serverity;
		public System.String Status;
		public System.String PhoneLogNotes;
		public System.String Queue;
		public System.DateTime CreateDate;
		public System.DateTime PhoneEndDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public System.Int32 ContactObjid;
		public System.Int32 SiteObjid;
		public System.Int32 PartRevisionObjid;
		public System.Int32 ContractObjid;
		public System.Int32 AddressObjid;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CloseSubcaseSetupProtocol
	{
		public CloseSubcaseSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String Status;
		public System.String Resolution;
		public System.String Summary;
		public System.String UserName;
		public System.DateTime CloseDate;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CloseCaseSetupProtocol
	{
		public CloseCaseSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String Status;
		public System.String Resolution;
		public System.String Summary;
		public System.String UserName;
		public System.DateTime CloseDate;
		public System.Double UnitsUsed;
		public Protocols.CaseTimeAndExpensesProtocol CaseTimeAndExpenses;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ChangeSubcaseStatusSetupProtocol
	{
		public ChangeSubcaseStatusSetupProtocol(){}

		public System.String SubcaseIDNum;
		public System.String NewStatus;
		public System.DateTime ChangeDate;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ChangeCaseStatusSetupProtocol
	{
		public ChangeCaseStatusSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String NewStatus;
		public System.DateTime ChangeDate;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ChangeCaseSiteSetupProtocol
	{
		public ChangeCaseSiteSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String SiteIDNum;
		public System.DateTime ChangeDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ChangeCaseContactSetupProtocol
	{
		public ChangeCaseContactSetupProtocol(){}

		public System.String CaseIDNum;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.DateTime ChangeDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
}
