//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web;
using System.Web.Services;

using FChoice.Toolkits.Clarify;
using FChoice.WebServices.Clarify;

namespace FChoice.WebServices.Clarify.Protocols.Support
{
	[Serializable]
	public class GetSubcaseTimeAndExpensesResultProtocol
	{
		public GetSubcaseTimeAndExpensesResultProtocol(){}
		
		internal GetSubcaseTimeAndExpensesResultProtocol(FChoice.Toolkits.Clarify.Support.GetSubcaseTimeAndExpensesResult result)
		{
			this.SubcaseTimeAndExpenses = new SubcaseTimeAndExpensesProtocol( result.SubcaseTimeAndExpenses );
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public Protocols.SubcaseTimeAndExpensesProtocol SubcaseTimeAndExpenses;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class GetCaseTimeAndExpensesResultProtocol
	{
		public GetCaseTimeAndExpensesResultProtocol(){}
		
		internal GetCaseTimeAndExpensesResultProtocol(FChoice.Toolkits.Clarify.Support.GetCaseTimeAndExpensesResult result)
		{
			this.CaseTimeAndExpenses = new CaseTimeAndExpensesProtocol( result.CaseTimeAndExpenses );
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public Protocols.CaseTimeAndExpensesProtocol CaseTimeAndExpenses;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class LogSubcaseEmailResultProtocol
	{
		public LogSubcaseEmailResultProtocol(){}
		
		internal LogSubcaseEmailResultProtocol(FChoice.Toolkits.Clarify.Support.LogSubcaseEmailResult result)
		{
			this.StatusChangeObjid = result.StatusChangeObjid;
			this.CommitmentObjid = result.CommitmentObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 StatusChangeObjid;
		public System.Int32 CommitmentObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class LogCaseEmailResultProtocol
	{
		public LogCaseEmailResultProtocol(){}
		
		internal LogCaseEmailResultProtocol(FChoice.Toolkits.Clarify.Support.LogCaseEmailResult result)
		{
			this.CommitmentObjid = result.CommitmentObjid;
			this.StatusChangeObjid = result.StatusChangeObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 CommitmentObjid;
		public System.Int32 StatusChangeObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class LogSubcaseNoteResultProtocol
	{
		public LogSubcaseNoteResultProtocol(){}
		
		internal LogSubcaseNoteResultProtocol(FChoice.Toolkits.Clarify.Support.LogSubcaseNoteResult result)
		{
			this.StatusChangeObjid = result.StatusChangeObjid;
			this.CommitmentObjid = result.CommitmentObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 StatusChangeObjid;
		public System.Int32 CommitmentObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class LogCaseNoteResultProtocol
	{
		public LogCaseNoteResultProtocol(){}
		
		internal LogCaseNoteResultProtocol(FChoice.Toolkits.Clarify.Support.LogCaseNoteResult result)
		{
			this.StatusChangeObjid = result.StatusChangeObjid;
			this.CommitmentObjid = result.CommitmentObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 StatusChangeObjid;
		public System.Int32 CommitmentObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class LogSubcaseResearchResultProtocol
	{
		public LogSubcaseResearchResultProtocol(){}
		
		internal LogSubcaseResearchResultProtocol(FChoice.Toolkits.Clarify.Support.LogSubcaseResearchResult result)
		{
			this.StatusChangeObjid = result.StatusChangeObjid;
			this.CommitmentObjid = result.CommitmentObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 StatusChangeObjid;
		public System.Int32 CommitmentObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class LogCaseResearchResultProtocol
	{
		public LogCaseResearchResultProtocol(){}
		
		internal LogCaseResearchResultProtocol(FChoice.Toolkits.Clarify.Support.LogCaseResearchResult result)
		{
			this.CommitmentObjid = result.CommitmentObjid;
			this.StatusChangeObjid = result.StatusChangeObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 CommitmentObjid;
		public System.Int32 StatusChangeObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class LogSubcasePhoneResultProtocol
	{
		public LogSubcasePhoneResultProtocol(){}
		
		internal LogSubcasePhoneResultProtocol(FChoice.Toolkits.Clarify.Support.LogSubcasePhoneResult result)
		{
			this.CommitmentObjid = result.CommitmentObjid;
			this.StatusChangeObjid = result.StatusChangeObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 CommitmentObjid;
		public System.Int32 StatusChangeObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class LogCasePhoneResultProtocol
	{
		public LogCasePhoneResultProtocol(){}
		
		internal LogCasePhoneResultProtocol(FChoice.Toolkits.Clarify.Support.LogCasePhoneResult result)
		{
			this.StatusChangeObjid = result.StatusChangeObjid;
			this.CommitmentObjid = result.CommitmentObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 StatusChangeObjid;
		public System.Int32 CommitmentObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
}
