//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web;
using System.Web.Services;

using FChoice.Toolkits.Clarify;
using FChoice.WebServices.Clarify;

namespace FChoice.WebServices.Clarify.Protocols.DepotRepair
{
	[Serializable]
	public class ApplyEcoSetupProtocol
	{
		public ApplyEcoSetupProtocol(){}

		public System.Int32 DemandDetailObjid;
		public System.String EcoHeaderIDNum;
		public System.String UserName;
		public System.DateTime CreateDate;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateDepotRepairMaterialSetupProtocol
	{
		public UpdateDepotRepairMaterialSetupProtocol(){}

		public System.Int32 MaterialLogObjid;
		public System.String RepairCode;
		public System.String FailureCode;
		public System.Int32 PartRevisionObjid;
		public System.Boolean IsBillable;
		public System.String BillTo;
		public System.String WorkCenter;
		public FChoice.Toolkits.Clarify.RepairPartDisposition Disposition;
		public System.String ReferenceDesignator;
		public System.String Notes;
		public System.String TransactionID;
		public System.String UserName;
		public System.DateTime CreateDate;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateDepotRepairLaborSetupProtocol
	{
		public UpdateDepotRepairLaborSetupProtocol(){}

		public System.Int32 TimeLogObjid;
		public System.String LaborType;
		public System.DateTime StartDate;
		public System.Int32 Duration;
		public System.Boolean IsBillable;
		public System.String BillTo;
		public System.String WorkCenter;
		public System.Double LaborRate;
		public System.String UserName;
		public System.DateTime CreateDate;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DeleteDepotRepairMaterialSetupProtocol
	{
		public DeleteDepotRepairMaterialSetupProtocol(){}

		public System.Int32 MaterialLogObjid;
		public System.DateTime CreateDate;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DeleteDepotRepairLaborSetupProtocol
	{
		public DeleteDepotRepairLaborSetupProtocol(){}

		public System.Int32 TimeLogObjid;
		public System.DateTime CreateDate;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateDepotRepairMaterialSetupProtocol
	{
		public CreateDepotRepairMaterialSetupProtocol(){}

		public System.Int32 DemandDetailObjid;
		public System.String RepairCode;
		public System.String FailureCode;
		public System.Int32 PartRevisionObjid;
		public System.Boolean IsBillable;
		public System.String BillTo;
		public System.String WorkCenter;
		public FChoice.Toolkits.Clarify.RepairPartDisposition Disposition;
		public System.String ReferenceDesignator;
		public System.String Notes;
		public System.String TransactionID;
		public System.String UserName;
		public System.DateTime CreateDate;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateDepotRepairLaborSetupProtocol
	{
		public CreateDepotRepairLaborSetupProtocol(){}

		public System.Int32 DemandDetailObjid;
		public System.String LaborType;
		public System.DateTime StartDate;
		public System.Int32 Duration;
		public System.Boolean IsBillable;
		public System.String BillTo;
		public System.String WorkCenter;
		public System.Double LaborRate;
		public System.String UserName;
		public System.DateTime CreateDate;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateEcoLaborDetailSetupProtocol
	{
		public UpdateEcoLaborDetailSetupProtocol(){}

		public System.Int32 EcoDetailObjid;
		public System.Boolean IsRequired;
		public System.String Status;
		public System.String LaborType;
		public System.Int32 ElapsedTime;
		public System.String Description;
		public System.String EcoHeaderIDNum;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateEcoMaterialDetailSetupProtocol
	{
		public UpdateEcoMaterialDetailSetupProtocol(){}

		public System.Int32 EcoDetailObjid;
		public System.Boolean IsRequired;
		public System.String Status;
		public System.Int32 ElapsedTime;
		public System.String Location;
		public System.String Description;
		public System.String EcoHeaderIDNum;
		public System.Int32 PartRevisionObjid;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DeleteEcoDetailSetupProtocol
	{
		public DeleteEcoDetailSetupProtocol(){}

		public System.Int32 EcoDetailObjid;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateEcoMaterialDetailSetupProtocol
	{
		public CreateEcoMaterialDetailSetupProtocol(){}

		public System.Boolean IsRequired;
		public System.String Status;
		public System.String Location;
		public System.String Description;
		public System.String EcoHeaderIDNum;
		public System.Int32 PartRevisionObjid;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateEcoLaborDetailSetupProtocol
	{
		public CreateEcoLaborDetailSetupProtocol(){}

		public System.Boolean IsRequired;
		public System.String Status;
		public System.String LaborType;
		public System.Int32 ElapsedTime;
		public System.String Description;
		public System.String EcoHeaderIDNum;
		public System.Int32 PartRevisionObjid;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DeleteEcoItemSetupProtocol
	{
		public DeleteEcoItemSetupProtocol(){}

		public System.Int32 EcoItemObjid;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateEcoItemSetupProtocol
	{
		public UpdateEcoItemSetupProtocol(){}

		public System.Int32 EcoItemObjid;
		public FChoice.Toolkits.Clarify.EcoItemAppliesTo AppliesTo;
		public System.Boolean IsActive;
		public System.String EcoHeaderIDNum;
		public System.Int32 ApplyPartRevisionObjid;
		public System.Int32 ResultPartRevisionObjid;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateEcoItemSetupProtocol
	{
		public CreateEcoItemSetupProtocol(){}

		public FChoice.Toolkits.Clarify.EcoItemAppliesTo AppliesTo;
		public System.Boolean IsActive;
		public System.String EcoHeaderIDNum;
		public System.Int32 ApplyPartRevisionObjid;
		public System.Int32 ResultPartRevisionObjid;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateEcoHeaderSetupProtocol
	{
		public CreateEcoHeaderSetupProtocol(){}

		public System.String EcoTitle;
		public System.String EcoType;
		public System.DateTime CreateDate;
		public System.String EffectType;
		public System.DateTime StartDate;
		public System.DateTime EndDate;
		public System.String Status;
		public System.String Description;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
}
