//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Web;
using System.Web.Services;
using Protocol = FChoice.WebServices.Clarify.Client.Protocols.DepotRepairToolkitSrv;
using FChoice.WebServices.Clarify.Client;

namespace FChoice.WebServices.Clarify.Client.DepotRepair
{
	public class DepotRepairToolkitWS
	{
		private Protocol.DepotRepairToolkitSrv toolkitProtocol;
		
		public DepotRepairToolkitWS(ClarifySessionWS session)
		{
			toolkitProtocol = new Protocol.DepotRepairToolkitSrv();
			toolkitProtocol.Url = new Uri( session.BaseUri, "DepotRepairToolkitSrv.asmx" ).ToString();
			toolkitProtocol.AuthenticationHeaderValue = new Protocol.AuthenticationHeader();
			
			toolkitProtocol.AuthenticationHeaderValue.SessionID = session.SessionToken;
		}
		
		public Protocol.ToolkitResultProtocol ApplyEco(Int32 demandDetailObjid, String ecoHeaderIDNum)
		{
			return toolkitProtocol.ApplyEco( demandDetailObjid, ecoHeaderIDNum );
		}
		
		public Protocol.ToolkitResultProtocol ApplyEco(ApplyEcoSetupWS setupParam)
		{
			return toolkitProtocol.ApplyEco( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateDepotRepairMaterial(Int32 materialLogObjid, Protocol.RepairPartDisposition disposition)
		{
			return toolkitProtocol.UpdateDepotRepairMaterial( materialLogObjid, disposition );
		}
		
		public Protocol.ToolkitResultProtocol UpdateDepotRepairMaterial(UpdateDepotRepairMaterialSetupWS setupParam)
		{
			return toolkitProtocol.UpdateDepotRepairMaterial( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateDepotRepairLabor(Int32 timeLogObjid)
		{
			return toolkitProtocol.UpdateDepotRepairLabor( timeLogObjid );
		}
		
		public Protocol.ToolkitResultProtocol UpdateDepotRepairLabor(UpdateDepotRepairLaborSetupWS setupParam)
		{
			return toolkitProtocol.UpdateDepotRepairLabor( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DeleteDepotRepairMaterial(Int32 materialLogObjid)
		{
			return toolkitProtocol.DeleteDepotRepairMaterial( materialLogObjid );
		}
		
		public Protocol.ToolkitResultProtocol DeleteDepotRepairMaterial(DeleteDepotRepairMaterialSetupWS setupParam)
		{
			return toolkitProtocol.DeleteDepotRepairMaterial( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DeleteDepotRepairLabor(Int32 timeLogObjid)
		{
			return toolkitProtocol.DeleteDepotRepairLabor( timeLogObjid );
		}
		
		public Protocol.ToolkitResultProtocol DeleteDepotRepairLabor(DeleteDepotRepairLaborSetupWS setupParam)
		{
			return toolkitProtocol.DeleteDepotRepairLabor( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol CreateDepotRepairMaterial(Int32 demandDetailObjid, Int32 partRevisionObjid, Protocol.RepairPartDisposition disposition)
		{
			return toolkitProtocol.CreateDepotRepairMaterial( demandDetailObjid, partRevisionObjid, disposition );
		}
		
		public Protocol.ToolkitResultProtocol CreateDepotRepairMaterial(CreateDepotRepairMaterialSetupWS setupParam)
		{
			return toolkitProtocol.CreateDepotRepairMaterial( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol CreateDepotRepairLabor(Int32 demandDetailObjid, DateTime startDate, System.Int32 duration)
		{
			return toolkitProtocol.CreateDepotRepairLabor( demandDetailObjid, startDate, duration );
		}
		
		public Protocol.ToolkitResultProtocol CreateDepotRepairLabor(CreateDepotRepairLaborSetupWS setupParam)
		{
			return toolkitProtocol.CreateDepotRepairLabor( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateEcoLaborDetail(Int32 ecoDetailObjid)
		{
			return toolkitProtocol.UpdateEcoLaborDetail( ecoDetailObjid );
		}
		
		public Protocol.ToolkitResultProtocol UpdateEcoLaborDetail(UpdateEcoLaborDetailSetupWS setupParam)
		{
			return toolkitProtocol.UpdateEcoLaborDetail( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateEcoMaterialDetail(Int32 ecoDetailObjid, Int32 partRevisionObjid)
		{
			return toolkitProtocol.UpdateEcoMaterialDetail( ecoDetailObjid, partRevisionObjid );
		}
		
		public Protocol.ToolkitResultProtocol UpdateEcoMaterialDetail(UpdateEcoMaterialDetailSetupWS setupParam)
		{
			return toolkitProtocol.UpdateEcoMaterialDetail( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DeleteEcoDetail(Int32 ecoDetailObjid)
		{
			return toolkitProtocol.DeleteEcoDetail( ecoDetailObjid );
		}
		
		public Protocol.ToolkitResultProtocol DeleteEcoDetail(DeleteEcoDetailSetupWS setupParam)
		{
			return toolkitProtocol.DeleteEcoDetail( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol CreateEcoMaterialDetail(Boolean isRequired, String ecoHeaderIDNum, Int32 partRevisionObjid)
		{
			return toolkitProtocol.CreateEcoMaterialDetail( isRequired, ecoHeaderIDNum, partRevisionObjid );
		}
		
		public Protocol.ToolkitResultProtocol CreateEcoMaterialDetail(CreateEcoMaterialDetailSetupWS setupParam)
		{
			return toolkitProtocol.CreateEcoMaterialDetail( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol CreateEcoLaborDetail(Boolean isRequired, System.Int32 elapsedTime, String ecoHeaderIDNum)
		{
			return toolkitProtocol.CreateEcoLaborDetail( isRequired, elapsedTime, ecoHeaderIDNum );
		}
		
		public Protocol.ToolkitResultProtocol CreateEcoLaborDetail(CreateEcoLaborDetailSetupWS setupParam)
		{
			return toolkitProtocol.CreateEcoLaborDetail( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DeleteEcoItem(Int32 ecoItemObjid)
		{
			return toolkitProtocol.DeleteEcoItem( ecoItemObjid );
		}
		
		public Protocol.ToolkitResultProtocol DeleteEcoItem(DeleteEcoItemSetupWS setupParam)
		{
			return toolkitProtocol.DeleteEcoItem( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateEcoItem(Int32 ecoItemObjid, Boolean isActive, String ecoHeaderIDNum)
		{
			return toolkitProtocol.UpdateEcoItem( ecoItemObjid, isActive, ecoHeaderIDNum );
		}
		
		public Protocol.ToolkitResultProtocol UpdateEcoItem(UpdateEcoItemSetupWS setupParam)
		{
			return toolkitProtocol.UpdateEcoItem( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol CreateEcoItem(Protocol.EcoItemAppliesTo appliesTo, Boolean isActive, String ecoHeaderIDNum, Int32 applyPartRevisionObjid, Int32 resultPartRevisionObjid)
		{
			return toolkitProtocol.CreateEcoItem( appliesTo, isActive, ecoHeaderIDNum, applyPartRevisionObjid, resultPartRevisionObjid );
		}
		
		public Protocol.ToolkitResultProtocol CreateEcoItem(CreateEcoItemSetupWS setupParam)
		{
			return toolkitProtocol.CreateEcoItem( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol CreateEcoHeader(DateTime startDate, DateTime endDate)
		{
			return toolkitProtocol.CreateEcoHeader( startDate, endDate );
		}
		
		public Protocol.ToolkitResultProtocol CreateEcoHeader(CreateEcoHeaderSetupWS setupParam)
		{
			return toolkitProtocol.CreateEcoHeader( setupParam.ToProtocol() );
		}
		
	}
}
