//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web;
using System.Web.Services;

using FChoice.WebServices.Clarify;

using Protocol = FChoice.WebServices.Clarify.Client.Protocols.DepotRepairToolkitSrv;

namespace FChoice.WebServices.Clarify.Client.DepotRepair
{
	#region ApplyEcoSetupWS
	public class ApplyEcoSetupWS
	{
		#region Constructors
		public ApplyEcoSetupWS(Int32 demandDetailObjid, String ecoHeaderIDNum)
		{
			ConstructorCue = 0;
			this.DemandDetailObjid = demandDetailObjid;
			this.EcoHeaderIDNum = ecoHeaderIDNum;
		}
		
		#endregion
		
		private Int32 _DemandDetailObjid;
		private String _EcoHeaderIDNum;
		private String _UserName;
		private DateTime _CreateDate;
		public Int32 DemandDetailObjid
		{
			get{ return _DemandDetailObjid; }
			set{ DirtyFieldFlags |= 1;_DemandDetailObjid = value; }
		}
		
		public String EcoHeaderIDNum
		{
			get{ return _EcoHeaderIDNum; }
			set{ DirtyFieldFlags |= 2;_EcoHeaderIDNum = value; }
		}
		
		public String UserName
		{
			get{ return _UserName; }
			set{ DirtyFieldFlags |= 4;_UserName = value; }
		}
		
		public DateTime CreateDate
		{
			get{ return _CreateDate; }
			set{ DirtyFieldFlags |= 8;_CreateDate = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.ApplyEcoSetupProtocol ToProtocol()
		{
			Protocol.ApplyEcoSetupProtocol protocol = new Protocol.ApplyEcoSetupProtocol();

			protocol.DemandDetailObjid = this.DemandDetailObjid;
			protocol.EcoHeaderIDNum = this.EcoHeaderIDNum;
			protocol.UserName = this.UserName;
			protocol.CreateDate = this.CreateDate;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region UpdateDepotRepairMaterialSetupWS
	public class UpdateDepotRepairMaterialSetupWS
	{
		#region Constructors
		public UpdateDepotRepairMaterialSetupWS(Int32 materialLogObjid, Protocol.RepairPartDisposition disposition)
		{
			ConstructorCue = 0;
			this.MaterialLogObjid = materialLogObjid;
			this.Disposition = disposition;
		}
		
		#endregion
		
		private Int32 _MaterialLogObjid;
		private String _RepairCode;
		private String _FailureCode;
		private Int32 _PartRevisionObjid;
		private Boolean _IsBillable;
		private String _BillTo;
		private String _WorkCenter;
		private Protocol.RepairPartDisposition _Disposition;
		private String _ReferenceDesignator;
		private String _Notes;
		private String _TransactionID;
		private String _UserName;
		private DateTime _CreateDate;
		public Int32 MaterialLogObjid
		{
			get{ return _MaterialLogObjid; }
			set{ DirtyFieldFlags |= 1;_MaterialLogObjid = value; }
		}
		
		public String RepairCode
		{
			get{ return _RepairCode; }
			set{ DirtyFieldFlags |= 2;_RepairCode = value; }
		}
		
		public String FailureCode
		{
			get{ return _FailureCode; }
			set{ DirtyFieldFlags |= 4;_FailureCode = value; }
		}
		
		public Int32 PartRevisionObjid
		{
			get{ return _PartRevisionObjid; }
			set{ DirtyFieldFlags |= 8;_PartRevisionObjid = value; }
		}
		
		public Boolean IsBillable
		{
			get{ return _IsBillable; }
			set{ DirtyFieldFlags |= 16;_IsBillable = value; }
		}
		
		public String BillTo
		{
			get{ return _BillTo; }
			set{ DirtyFieldFlags |= 32;_BillTo = value; }
		}
		
		public String WorkCenter
		{
			get{ return _WorkCenter; }
			set{ DirtyFieldFlags |= 64;_WorkCenter = value; }
		}
		
		public Protocol.RepairPartDisposition Disposition
		{
			get{ return _Disposition; }
			set{ DirtyFieldFlags |= 128;_Disposition = value; }
		}
		
		public String ReferenceDesignator
		{
			get{ return _ReferenceDesignator; }
			set{ DirtyFieldFlags |= 256;_ReferenceDesignator = value; }
		}
		
		public String Notes
		{
			get{ return _Notes; }
			set{ DirtyFieldFlags |= 512;_Notes = value; }
		}
		
		public String TransactionID
		{
			get{ return _TransactionID; }
			set{ DirtyFieldFlags |= 1024;_TransactionID = value; }
		}
		
		public String UserName
		{
			get{ return _UserName; }
			set{ DirtyFieldFlags |= 2048;_UserName = value; }
		}
		
		public DateTime CreateDate
		{
			get{ return _CreateDate; }
			set{ DirtyFieldFlags |= 4096;_CreateDate = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.UpdateDepotRepairMaterialSetupProtocol ToProtocol()
		{
			Protocol.UpdateDepotRepairMaterialSetupProtocol protocol = new Protocol.UpdateDepotRepairMaterialSetupProtocol();

			protocol.MaterialLogObjid = this.MaterialLogObjid;
			protocol.RepairCode = this.RepairCode;
			protocol.FailureCode = this.FailureCode;
			protocol.PartRevisionObjid = this.PartRevisionObjid;
			protocol.IsBillable = this.IsBillable;
			protocol.BillTo = this.BillTo;
			protocol.WorkCenter = this.WorkCenter;
			protocol.Disposition = this.Disposition;
			protocol.ReferenceDesignator = this.ReferenceDesignator;
			protocol.Notes = this.Notes;
			protocol.TransactionID = this.TransactionID;
			protocol.UserName = this.UserName;
			protocol.CreateDate = this.CreateDate;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region UpdateDepotRepairLaborSetupWS
	public class UpdateDepotRepairLaborSetupWS
	{
		#region Constructors
		public UpdateDepotRepairLaborSetupWS(Int32 timeLogObjid)
		{
			ConstructorCue = 0;
			this.TimeLogObjid = timeLogObjid;
		}
		
		#endregion
		
		private Int32 _TimeLogObjid;
		private String _LaborType;
		private DateTime _StartDate;
		private System.Int32 _Duration;
		private Boolean _IsBillable;
		private String _BillTo;
		private String _WorkCenter;
		private Double _LaborRate;
		private String _UserName;
		private DateTime _CreateDate;
		public Int32 TimeLogObjid
		{
			get{ return _TimeLogObjid; }
			set{ DirtyFieldFlags |= 1;_TimeLogObjid = value; }
		}
		
		public String LaborType
		{
			get{ return _LaborType; }
			set{ DirtyFieldFlags |= 2;_LaborType = value; }
		}
		
		public DateTime StartDate
		{
			get{ return _StartDate; }
			set{ DirtyFieldFlags |= 4;_StartDate = value; }
		}
		
		public System.Int32 Duration
		{
			get{ return _Duration; }
			set{ DirtyFieldFlags |= 8;_Duration = value; }
		}
		
		public Boolean IsBillable
		{
			get{ return _IsBillable; }
			set{ DirtyFieldFlags |= 16;_IsBillable = value; }
		}
		
		public String BillTo
		{
			get{ return _BillTo; }
			set{ DirtyFieldFlags |= 32;_BillTo = value; }
		}
		
		public String WorkCenter
		{
			get{ return _WorkCenter; }
			set{ DirtyFieldFlags |= 64;_WorkCenter = value; }
		}
		
		public Double LaborRate
		{
			get{ return _LaborRate; }
			set{ DirtyFieldFlags |= 128;_LaborRate = value; }
		}
		
		public String UserName
		{
			get{ return _UserName; }
			set{ DirtyFieldFlags |= 256;_UserName = value; }
		}
		
		public DateTime CreateDate
		{
			get{ return _CreateDate; }
			set{ DirtyFieldFlags |= 512;_CreateDate = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.UpdateDepotRepairLaborSetupProtocol ToProtocol()
		{
			Protocol.UpdateDepotRepairLaborSetupProtocol protocol = new Protocol.UpdateDepotRepairLaborSetupProtocol();

			protocol.TimeLogObjid = this.TimeLogObjid;
			protocol.LaborType = this.LaborType;
			protocol.StartDate = this.StartDate;
			protocol.Duration = this.Duration;
			protocol.IsBillable = this.IsBillable;
			protocol.BillTo = this.BillTo;
			protocol.WorkCenter = this.WorkCenter;
			protocol.LaborRate = this.LaborRate;
			protocol.UserName = this.UserName;
			protocol.CreateDate = this.CreateDate;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region DeleteDepotRepairMaterialSetupWS
	public class DeleteDepotRepairMaterialSetupWS
	{
		#region Constructors
		public DeleteDepotRepairMaterialSetupWS(Int32 materialLogObjid)
		{
			ConstructorCue = 0;
			this.MaterialLogObjid = materialLogObjid;
		}
		
		#endregion
		
		private Int32 _MaterialLogObjid;
		private DateTime _CreateDate;
		public Int32 MaterialLogObjid
		{
			get{ return _MaterialLogObjid; }
			set{ DirtyFieldFlags |= 1;_MaterialLogObjid = value; }
		}
		
		public DateTime CreateDate
		{
			get{ return _CreateDate; }
			set{ DirtyFieldFlags |= 2;_CreateDate = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.DeleteDepotRepairMaterialSetupProtocol ToProtocol()
		{
			Protocol.DeleteDepotRepairMaterialSetupProtocol protocol = new Protocol.DeleteDepotRepairMaterialSetupProtocol();

			protocol.MaterialLogObjid = this.MaterialLogObjid;
			protocol.CreateDate = this.CreateDate;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region DeleteDepotRepairLaborSetupWS
	public class DeleteDepotRepairLaborSetupWS
	{
		#region Constructors
		public DeleteDepotRepairLaborSetupWS(Int32 timeLogObjid)
		{
			ConstructorCue = 0;
			this.TimeLogObjid = timeLogObjid;
		}
		
		#endregion
		
		private Int32 _TimeLogObjid;
		private DateTime _CreateDate;
		public Int32 TimeLogObjid
		{
			get{ return _TimeLogObjid; }
			set{ DirtyFieldFlags |= 1;_TimeLogObjid = value; }
		}
		
		public DateTime CreateDate
		{
			get{ return _CreateDate; }
			set{ DirtyFieldFlags |= 2;_CreateDate = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.DeleteDepotRepairLaborSetupProtocol ToProtocol()
		{
			Protocol.DeleteDepotRepairLaborSetupProtocol protocol = new Protocol.DeleteDepotRepairLaborSetupProtocol();

			protocol.TimeLogObjid = this.TimeLogObjid;
			protocol.CreateDate = this.CreateDate;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region CreateDepotRepairMaterialSetupWS
	public class CreateDepotRepairMaterialSetupWS
	{
		#region Constructors
		public CreateDepotRepairMaterialSetupWS(Int32 demandDetailObjid, Int32 partRevisionObjid, Protocol.RepairPartDisposition disposition)
		{
			ConstructorCue = 0;
			this.DemandDetailObjid = demandDetailObjid;
			this.PartRevisionObjid = partRevisionObjid;
			this.Disposition = disposition;
		}
		
		#endregion
		
		private Int32 _DemandDetailObjid;
		private String _RepairCode;
		private String _FailureCode;
		private Int32 _PartRevisionObjid;
		private Boolean _IsBillable;
		private String _BillTo;
		private String _WorkCenter;
		private Protocol.RepairPartDisposition _Disposition;
		private String _ReferenceDesignator;
		private String _Notes;
		private String _TransactionID;
		private String _UserName;
		private DateTime _CreateDate;
		public Int32 DemandDetailObjid
		{
			get{ return _DemandDetailObjid; }
			set{ DirtyFieldFlags |= 1;_DemandDetailObjid = value; }
		}
		
		public String RepairCode
		{
			get{ return _RepairCode; }
			set{ DirtyFieldFlags |= 2;_RepairCode = value; }
		}
		
		public String FailureCode
		{
			get{ return _FailureCode; }
			set{ DirtyFieldFlags |= 4;_FailureCode = value; }
		}
		
		public Int32 PartRevisionObjid
		{
			get{ return _PartRevisionObjid; }
			set{ DirtyFieldFlags |= 8;_PartRevisionObjid = value; }
		}
		
		public Boolean IsBillable
		{
			get{ return _IsBillable; }
			set{ DirtyFieldFlags |= 16;_IsBillable = value; }
		}
		
		public String BillTo
		{
			get{ return _BillTo; }
			set{ DirtyFieldFlags |= 32;_BillTo = value; }
		}
		
		public String WorkCenter
		{
			get{ return _WorkCenter; }
			set{ DirtyFieldFlags |= 64;_WorkCenter = value; }
		}
		
		public Protocol.RepairPartDisposition Disposition
		{
			get{ return _Disposition; }
			set{ DirtyFieldFlags |= 128;_Disposition = value; }
		}
		
		public String ReferenceDesignator
		{
			get{ return _ReferenceDesignator; }
			set{ DirtyFieldFlags |= 256;_ReferenceDesignator = value; }
		}
		
		public String Notes
		{
			get{ return _Notes; }
			set{ DirtyFieldFlags |= 512;_Notes = value; }
		}
		
		public String TransactionID
		{
			get{ return _TransactionID; }
			set{ DirtyFieldFlags |= 1024;_TransactionID = value; }
		}
		
		public String UserName
		{
			get{ return _UserName; }
			set{ DirtyFieldFlags |= 2048;_UserName = value; }
		}
		
		public DateTime CreateDate
		{
			get{ return _CreateDate; }
			set{ DirtyFieldFlags |= 4096;_CreateDate = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.CreateDepotRepairMaterialSetupProtocol ToProtocol()
		{
			Protocol.CreateDepotRepairMaterialSetupProtocol protocol = new Protocol.CreateDepotRepairMaterialSetupProtocol();

			protocol.DemandDetailObjid = this.DemandDetailObjid;
			protocol.RepairCode = this.RepairCode;
			protocol.FailureCode = this.FailureCode;
			protocol.PartRevisionObjid = this.PartRevisionObjid;
			protocol.IsBillable = this.IsBillable;
			protocol.BillTo = this.BillTo;
			protocol.WorkCenter = this.WorkCenter;
			protocol.Disposition = this.Disposition;
			protocol.ReferenceDesignator = this.ReferenceDesignator;
			protocol.Notes = this.Notes;
			protocol.TransactionID = this.TransactionID;
			protocol.UserName = this.UserName;
			protocol.CreateDate = this.CreateDate;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region CreateDepotRepairLaborSetupWS
	public class CreateDepotRepairLaborSetupWS
	{
		#region Constructors
		public CreateDepotRepairLaborSetupWS(Int32 demandDetailObjid, DateTime startDate, System.Int32 duration)
		{
			ConstructorCue = 0;
			this.DemandDetailObjid = demandDetailObjid;
			this.StartDate = startDate;
			this.Duration = duration;
		}
		
		#endregion
		
		private Int32 _DemandDetailObjid;
		private String _LaborType;
		private DateTime _StartDate;
		private System.Int32 _Duration;
		private Boolean _IsBillable;
		private String _BillTo;
		private String _WorkCenter;
		private Double _LaborRate;
		private String _UserName;
		private DateTime _CreateDate;
		public Int32 DemandDetailObjid
		{
			get{ return _DemandDetailObjid; }
			set{ DirtyFieldFlags |= 1;_DemandDetailObjid = value; }
		}
		
		public String LaborType
		{
			get{ return _LaborType; }
			set{ DirtyFieldFlags |= 2;_LaborType = value; }
		}
		
		public DateTime StartDate
		{
			get{ return _StartDate; }
			set{ DirtyFieldFlags |= 4;_StartDate = value; }
		}
		
		public System.Int32 Duration
		{
			get{ return _Duration; }
			set{ DirtyFieldFlags |= 8;_Duration = value; }
		}
		
		public Boolean IsBillable
		{
			get{ return _IsBillable; }
			set{ DirtyFieldFlags |= 16;_IsBillable = value; }
		}
		
		public String BillTo
		{
			get{ return _BillTo; }
			set{ DirtyFieldFlags |= 32;_BillTo = value; }
		}
		
		public String WorkCenter
		{
			get{ return _WorkCenter; }
			set{ DirtyFieldFlags |= 64;_WorkCenter = value; }
		}
		
		public Double LaborRate
		{
			get{ return _LaborRate; }
			set{ DirtyFieldFlags |= 128;_LaborRate = value; }
		}
		
		public String UserName
		{
			get{ return _UserName; }
			set{ DirtyFieldFlags |= 256;_UserName = value; }
		}
		
		public DateTime CreateDate
		{
			get{ return _CreateDate; }
			set{ DirtyFieldFlags |= 512;_CreateDate = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.CreateDepotRepairLaborSetupProtocol ToProtocol()
		{
			Protocol.CreateDepotRepairLaborSetupProtocol protocol = new Protocol.CreateDepotRepairLaborSetupProtocol();

			protocol.DemandDetailObjid = this.DemandDetailObjid;
			protocol.LaborType = this.LaborType;
			protocol.StartDate = this.StartDate;
			protocol.Duration = this.Duration;
			protocol.IsBillable = this.IsBillable;
			protocol.BillTo = this.BillTo;
			protocol.WorkCenter = this.WorkCenter;
			protocol.LaborRate = this.LaborRate;
			protocol.UserName = this.UserName;
			protocol.CreateDate = this.CreateDate;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region UpdateEcoLaborDetailSetupWS
	public class UpdateEcoLaborDetailSetupWS
	{
		#region Constructors
		public UpdateEcoLaborDetailSetupWS(Int32 ecoDetailObjid)
		{
			ConstructorCue = 0;
			this.EcoDetailObjid = ecoDetailObjid;
		}
		
		#endregion
		
		private Int32 _EcoDetailObjid;
		private Boolean _IsRequired;
		private String _Status;
		private String _LaborType;
		private System.Int32 _ElapsedTime;
		private String _Description;
		private String _EcoHeaderIDNum;
		public Int32 EcoDetailObjid
		{
			get{ return _EcoDetailObjid; }
			set{ DirtyFieldFlags |= 1;_EcoDetailObjid = value; }
		}
		
		public Boolean IsRequired
		{
			get{ return _IsRequired; }
			set{ DirtyFieldFlags |= 4;_IsRequired = value; }
		}
		
		public String Status
		{
			get{ return _Status; }
			set{ DirtyFieldFlags |= 8;_Status = value; }
		}
		
		public String LaborType
		{
			get{ return _LaborType; }
			set{ DirtyFieldFlags |= 16;_LaborType = value; }
		}
		
		public System.Int32 ElapsedTime
		{
			get{ return _ElapsedTime; }
			set{ DirtyFieldFlags |= 32;_ElapsedTime = value; }
		}
		
		public String Description
		{
			get{ return _Description; }
			set{ DirtyFieldFlags |= 128;_Description = value; }
		}
		
		public String EcoHeaderIDNum
		{
			get{ return _EcoHeaderIDNum; }
			set{ DirtyFieldFlags |= 256;_EcoHeaderIDNum = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.UpdateEcoLaborDetailSetupProtocol ToProtocol()
		{
			Protocol.UpdateEcoLaborDetailSetupProtocol protocol = new Protocol.UpdateEcoLaborDetailSetupProtocol();

			protocol.EcoDetailObjid = this.EcoDetailObjid;
			protocol.IsRequired = this.IsRequired;
			protocol.Status = this.Status;
			protocol.LaborType = this.LaborType;
			protocol.ElapsedTime = this.ElapsedTime;
			protocol.Description = this.Description;
			protocol.EcoHeaderIDNum = this.EcoHeaderIDNum;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region UpdateEcoMaterialDetailSetupWS
	public class UpdateEcoMaterialDetailSetupWS
	{
		#region Constructors
		public UpdateEcoMaterialDetailSetupWS(Int32 ecoDetailObjid, Int32 partRevisionObjid)
		{
			ConstructorCue = 0;
			this.EcoDetailObjid = ecoDetailObjid;
			this.PartRevisionObjid = partRevisionObjid;
		}
		
		#endregion
		
		private Int32 _EcoDetailObjid;
		private Boolean _IsRequired;
		private String _Status;
		private System.Int32 _ElapsedTime;
		private String _Location;
		private String _Description;
		private String _EcoHeaderIDNum;
		private Int32 _PartRevisionObjid;
		public Int32 EcoDetailObjid
		{
			get{ return _EcoDetailObjid; }
			set{ DirtyFieldFlags |= 1;_EcoDetailObjid = value; }
		}
		
		public Boolean IsRequired
		{
			get{ return _IsRequired; }
			set{ DirtyFieldFlags |= 4;_IsRequired = value; }
		}
		
		public String Status
		{
			get{ return _Status; }
			set{ DirtyFieldFlags |= 8;_Status = value; }
		}
		
		public System.Int32 ElapsedTime
		{
			get{ return _ElapsedTime; }
			set{ DirtyFieldFlags |= 32;_ElapsedTime = value; }
		}
		
		public String Location
		{
			get{ return _Location; }
			set{ DirtyFieldFlags |= 64;_Location = value; }
		}
		
		public String Description
		{
			get{ return _Description; }
			set{ DirtyFieldFlags |= 128;_Description = value; }
		}
		
		public String EcoHeaderIDNum
		{
			get{ return _EcoHeaderIDNum; }
			set{ DirtyFieldFlags |= 256;_EcoHeaderIDNum = value; }
		}
		
		public Int32 PartRevisionObjid
		{
			get{ return _PartRevisionObjid; }
			set{ DirtyFieldFlags |= 512;_PartRevisionObjid = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.UpdateEcoMaterialDetailSetupProtocol ToProtocol()
		{
			Protocol.UpdateEcoMaterialDetailSetupProtocol protocol = new Protocol.UpdateEcoMaterialDetailSetupProtocol();

			protocol.EcoDetailObjid = this.EcoDetailObjid;
			protocol.IsRequired = this.IsRequired;
			protocol.Status = this.Status;
			protocol.ElapsedTime = this.ElapsedTime;
			protocol.Location = this.Location;
			protocol.Description = this.Description;
			protocol.EcoHeaderIDNum = this.EcoHeaderIDNum;
			protocol.PartRevisionObjid = this.PartRevisionObjid;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region DeleteEcoDetailSetupWS
	public class DeleteEcoDetailSetupWS
	{
		#region Constructors
		public DeleteEcoDetailSetupWS(Int32 ecoDetailObjid)
		{
			ConstructorCue = 0;
			this.EcoDetailObjid = ecoDetailObjid;
		}
		
		#endregion
		
		private Int32 _EcoDetailObjid;
		public Int32 EcoDetailObjid
		{
			get{ return _EcoDetailObjid; }
			set{ DirtyFieldFlags |= 1;_EcoDetailObjid = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.DeleteEcoDetailSetupProtocol ToProtocol()
		{
			Protocol.DeleteEcoDetailSetupProtocol protocol = new Protocol.DeleteEcoDetailSetupProtocol();

			protocol.EcoDetailObjid = this.EcoDetailObjid;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region CreateEcoMaterialDetailSetupWS
	public class CreateEcoMaterialDetailSetupWS
	{
		#region Constructors
		public CreateEcoMaterialDetailSetupWS(Boolean isRequired, String ecoHeaderIDNum, Int32 partRevisionObjid)
		{
			ConstructorCue = 0;
			this.IsRequired = isRequired;
			this.EcoHeaderIDNum = ecoHeaderIDNum;
			this.PartRevisionObjid = partRevisionObjid;
		}
		
		#endregion
		
		private Boolean _IsRequired;
		private String _Status;
		private String _Location;
		private String _Description;
		private String _EcoHeaderIDNum;
		private Int32 _PartRevisionObjid;
		public Boolean IsRequired
		{
			get{ return _IsRequired; }
			set{ DirtyFieldFlags |= 2;_IsRequired = value; }
		}
		
		public String Status
		{
			get{ return _Status; }
			set{ DirtyFieldFlags |= 4;_Status = value; }
		}
		
		public String Location
		{
			get{ return _Location; }
			set{ DirtyFieldFlags |= 32;_Location = value; }
		}
		
		public String Description
		{
			get{ return _Description; }
			set{ DirtyFieldFlags |= 64;_Description = value; }
		}
		
		public String EcoHeaderIDNum
		{
			get{ return _EcoHeaderIDNum; }
			set{ DirtyFieldFlags |= 128;_EcoHeaderIDNum = value; }
		}
		
		public Int32 PartRevisionObjid
		{
			get{ return _PartRevisionObjid; }
			set{ DirtyFieldFlags |= 256;_PartRevisionObjid = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.CreateEcoMaterialDetailSetupProtocol ToProtocol()
		{
			Protocol.CreateEcoMaterialDetailSetupProtocol protocol = new Protocol.CreateEcoMaterialDetailSetupProtocol();

			protocol.IsRequired = this.IsRequired;
			protocol.Status = this.Status;
			protocol.Location = this.Location;
			protocol.Description = this.Description;
			protocol.EcoHeaderIDNum = this.EcoHeaderIDNum;
			protocol.PartRevisionObjid = this.PartRevisionObjid;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region CreateEcoLaborDetailSetupWS
	public class CreateEcoLaborDetailSetupWS
	{
		#region Constructors
		public CreateEcoLaborDetailSetupWS(Boolean isRequired, System.Int32 elapsedTime, String ecoHeaderIDNum)
		{
			ConstructorCue = 0;
			this.IsRequired = isRequired;
			this.ElapsedTime = elapsedTime;
			this.EcoHeaderIDNum = ecoHeaderIDNum;
		}
		
		#endregion
		
		private Boolean _IsRequired;
		private String _Status;
		private String _LaborType;
		private System.Int32 _ElapsedTime;
		private String _Description;
		private String _EcoHeaderIDNum;
		private Int32 _PartRevisionObjid;
		public Boolean IsRequired
		{
			get{ return _IsRequired; }
			set{ DirtyFieldFlags |= 2;_IsRequired = value; }
		}
		
		public String Status
		{
			get{ return _Status; }
			set{ DirtyFieldFlags |= 4;_Status = value; }
		}
		
		public String LaborType
		{
			get{ return _LaborType; }
			set{ DirtyFieldFlags |= 8;_LaborType = value; }
		}
		
		public System.Int32 ElapsedTime
		{
			get{ return _ElapsedTime; }
			set{ DirtyFieldFlags |= 16;_ElapsedTime = value; }
		}
		
		public String Description
		{
			get{ return _Description; }
			set{ DirtyFieldFlags |= 64;_Description = value; }
		}
		
		public String EcoHeaderIDNum
		{
			get{ return _EcoHeaderIDNum; }
			set{ DirtyFieldFlags |= 128;_EcoHeaderIDNum = value; }
		}
		
		public Int32 PartRevisionObjid
		{
			get{ return _PartRevisionObjid; }
			set{ DirtyFieldFlags |= 256;_PartRevisionObjid = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.CreateEcoLaborDetailSetupProtocol ToProtocol()
		{
			Protocol.CreateEcoLaborDetailSetupProtocol protocol = new Protocol.CreateEcoLaborDetailSetupProtocol();

			protocol.IsRequired = this.IsRequired;
			protocol.Status = this.Status;
			protocol.LaborType = this.LaborType;
			protocol.ElapsedTime = this.ElapsedTime;
			protocol.Description = this.Description;
			protocol.EcoHeaderIDNum = this.EcoHeaderIDNum;
			protocol.PartRevisionObjid = this.PartRevisionObjid;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region DeleteEcoItemSetupWS
	public class DeleteEcoItemSetupWS
	{
		#region Constructors
		public DeleteEcoItemSetupWS(Int32 ecoItemObjid)
		{
			ConstructorCue = 0;
			this.EcoItemObjid = ecoItemObjid;
		}
		
		#endregion
		
		private Int32 _EcoItemObjid;
		public Int32 EcoItemObjid
		{
			get{ return _EcoItemObjid; }
			set{ DirtyFieldFlags |= 1;_EcoItemObjid = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.DeleteEcoItemSetupProtocol ToProtocol()
		{
			Protocol.DeleteEcoItemSetupProtocol protocol = new Protocol.DeleteEcoItemSetupProtocol();

			protocol.EcoItemObjid = this.EcoItemObjid;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region UpdateEcoItemSetupWS
	public class UpdateEcoItemSetupWS
	{
		#region Constructors
		public UpdateEcoItemSetupWS(Int32 ecoItemObjid, Boolean isActive, String ecoHeaderIDNum)
		{
			ConstructorCue = 0;
			this.EcoItemObjid = ecoItemObjid;
			this.IsActive = isActive;
			this.EcoHeaderIDNum = ecoHeaderIDNum;
		}
		
		#endregion
		
		private Int32 _EcoItemObjid;
		private Protocol.EcoItemAppliesTo _AppliesTo;
		private Boolean _IsActive;
		private String _EcoHeaderIDNum;
		private Int32 _ApplyPartRevisionObjid;
		private Int32 _ResultPartRevisionObjid;
		public Int32 EcoItemObjid
		{
			get{ return _EcoItemObjid; }
			set{ DirtyFieldFlags |= 1;_EcoItemObjid = value; }
		}
		
		public Protocol.EcoItemAppliesTo AppliesTo
		{
			get{ return _AppliesTo; }
			set{ DirtyFieldFlags |= 2;_AppliesTo = value; }
		}
		
		public Boolean IsActive
		{
			get{ return _IsActive; }
			set{ DirtyFieldFlags |= 4;_IsActive = value; }
		}
		
		public String EcoHeaderIDNum
		{
			get{ return _EcoHeaderIDNum; }
			set{ DirtyFieldFlags |= 8;_EcoHeaderIDNum = value; }
		}
		
		public Int32 ApplyPartRevisionObjid
		{
			get{ return _ApplyPartRevisionObjid; }
			set{ DirtyFieldFlags |= 16;_ApplyPartRevisionObjid = value; }
		}
		
		public Int32 ResultPartRevisionObjid
		{
			get{ return _ResultPartRevisionObjid; }
			set{ DirtyFieldFlags |= 32;_ResultPartRevisionObjid = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.UpdateEcoItemSetupProtocol ToProtocol()
		{
			Protocol.UpdateEcoItemSetupProtocol protocol = new Protocol.UpdateEcoItemSetupProtocol();

			protocol.EcoItemObjid = this.EcoItemObjid;
			protocol.AppliesTo = this.AppliesTo;
			protocol.IsActive = this.IsActive;
			protocol.EcoHeaderIDNum = this.EcoHeaderIDNum;
			protocol.ApplyPartRevisionObjid = this.ApplyPartRevisionObjid;
			protocol.ResultPartRevisionObjid = this.ResultPartRevisionObjid;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region CreateEcoItemSetupWS
	public class CreateEcoItemSetupWS
	{
		#region Constructors
		public CreateEcoItemSetupWS(Protocol.EcoItemAppliesTo appliesTo, Boolean isActive, String ecoHeaderIDNum, Int32 applyPartRevisionObjid, Int32 resultPartRevisionObjid)
		{
			ConstructorCue = 0;
			this.AppliesTo = appliesTo;
			this.IsActive = isActive;
			this.EcoHeaderIDNum = ecoHeaderIDNum;
			this.ApplyPartRevisionObjid = applyPartRevisionObjid;
			this.ResultPartRevisionObjid = resultPartRevisionObjid;
		}
		
		#endregion
		
		private Protocol.EcoItemAppliesTo _AppliesTo;
		private Boolean _IsActive;
		private String _EcoHeaderIDNum;
		private Int32 _ApplyPartRevisionObjid;
		private Int32 _ResultPartRevisionObjid;
		public Protocol.EcoItemAppliesTo AppliesTo
		{
			get{ return _AppliesTo; }
			set{ DirtyFieldFlags |= 1;_AppliesTo = value; }
		}
		
		public Boolean IsActive
		{
			get{ return _IsActive; }
			set{ DirtyFieldFlags |= 2;_IsActive = value; }
		}
		
		public String EcoHeaderIDNum
		{
			get{ return _EcoHeaderIDNum; }
			set{ DirtyFieldFlags |= 4;_EcoHeaderIDNum = value; }
		}
		
		public Int32 ApplyPartRevisionObjid
		{
			get{ return _ApplyPartRevisionObjid; }
			set{ DirtyFieldFlags |= 8;_ApplyPartRevisionObjid = value; }
		}
		
		public Int32 ResultPartRevisionObjid
		{
			get{ return _ResultPartRevisionObjid; }
			set{ DirtyFieldFlags |= 16;_ResultPartRevisionObjid = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.CreateEcoItemSetupProtocol ToProtocol()
		{
			Protocol.CreateEcoItemSetupProtocol protocol = new Protocol.CreateEcoItemSetupProtocol();

			protocol.AppliesTo = this.AppliesTo;
			protocol.IsActive = this.IsActive;
			protocol.EcoHeaderIDNum = this.EcoHeaderIDNum;
			protocol.ApplyPartRevisionObjid = this.ApplyPartRevisionObjid;
			protocol.ResultPartRevisionObjid = this.ResultPartRevisionObjid;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
	#region CreateEcoHeaderSetupWS
	public class CreateEcoHeaderSetupWS
	{
		#region Constructors
		public CreateEcoHeaderSetupWS(DateTime startDate, DateTime endDate)
		{
			ConstructorCue = 0;
			this.StartDate = startDate;
			this.EndDate = endDate;
		}
		
		#endregion
		
		private String _EcoTitle;
		private String _EcoType;
		private DateTime _CreateDate;
		private String _EffectType;
		private DateTime _StartDate;
		private DateTime _EndDate;
		private String _Status;
		private String _Description;
		public String EcoTitle
		{
			get{ return _EcoTitle; }
			set{ DirtyFieldFlags |= 1;_EcoTitle = value; }
		}
		
		public String EcoType
		{
			get{ return _EcoType; }
			set{ DirtyFieldFlags |= 2;_EcoType = value; }
		}
		
		public DateTime CreateDate
		{
			get{ return _CreateDate; }
			set{ DirtyFieldFlags |= 4;_CreateDate = value; }
		}
		
		public String EffectType
		{
			get{ return _EffectType; }
			set{ DirtyFieldFlags |= 8;_EffectType = value; }
		}
		
		public DateTime StartDate
		{
			get{ return _StartDate; }
			set{ DirtyFieldFlags |= 16;_StartDate = value; }
		}
		
		public DateTime EndDate
		{
			get{ return _EndDate; }
			set{ DirtyFieldFlags |= 32;_EndDate = value; }
		}
		
		public String Status
		{
			get{ return _Status; }
			set{ DirtyFieldFlags |= 64;_Status = value; }
		}
		
		public String Description
		{
			get{ return _Description; }
			set{ DirtyFieldFlags |= 128;_Description = value; }
		}
		

		internal int DirtyFieldFlags;
		internal int ConstructorCue;
		
		internal Protocol.CreateEcoHeaderSetupProtocol ToProtocol()
		{
			Protocol.CreateEcoHeaderSetupProtocol protocol = new Protocol.CreateEcoHeaderSetupProtocol();

			protocol.EcoTitle = this.EcoTitle;
			protocol.EcoType = this.EcoType;
			protocol.CreateDate = this.CreateDate;
			protocol.EffectType = this.EffectType;
			protocol.StartDate = this.StartDate;
			protocol.EndDate = this.EndDate;
			protocol.Status = this.Status;
			protocol.Description = this.Description;
			protocol.ConstructorCue = this.ConstructorCue;
			protocol.DirtyFieldFlags = this.DirtyFieldFlags;
			
			return protocol;			
		}
		
	}
	#endregion
	
}
