//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
namespace FChoice.WebServices.Clarify.Client.Protocols.QualityToolkitSrv {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QualityToolkitSrvSoap", Namespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AdditionalFieldProtocol))]
    public class QualityToolkitSrv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public AuthenticationHeader AuthenticationHeaderValue;
        
        /// <remarks/>
        public QualityToolkitSrv() {
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/F" +
"ixFailed", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol FixFailed(string crIDNum) {
            object[] results = this.Invoke("FixFailed", new object[] {
                        crIDNum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFixFailed(string crIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FixFailed", new object[] {
                        crIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndFixFailed(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="FixFailed1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/F" +
"ixFailed2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("FixFailed2Result")]
        public ToolkitResultProtocol FixFailed(FixFailedSetupProtocol setupParam) {
            object[] results = this.Invoke("FixFailed1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFixFailed1(FixFailedSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FixFailed1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndFixFailed1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/L" +
"ogCREmail", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol LogCREmail(string crIDNum) {
            object[] results = this.Invoke("LogCREmail", new object[] {
                        crIDNum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogCREmail(string crIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LogCREmail", new object[] {
                        crIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndLogCREmail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="LogCREmail1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/L" +
"ogCREmail2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("LogCREmail2Result")]
        public ToolkitResultProtocol LogCREmail(LogCREmailSetupProtocol setupParam) {
            object[] results = this.Invoke("LogCREmail1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogCREmail1(LogCREmailSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LogCREmail1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndLogCREmail1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/R" +
"eplicateCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol ReplicateCR(string crIDNum) {
            object[] results = this.Invoke("ReplicateCR", new object[] {
                        crIDNum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReplicateCR(string crIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReplicateCR", new object[] {
                        crIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndReplicateCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="ReplicateCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/R" +
"eplicateCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("ReplicateCR2Result")]
        public ToolkitResultProtocol ReplicateCR(ReplicateCRSetupProtocol setupParam) {
            object[] results = this.Invoke("ReplicateCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReplicateCR1(ReplicateCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReplicateCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndReplicateCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/U" +
"pdateCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol UpdateCR(string crIDNum) {
            object[] results = this.Invoke("UpdateCR", new object[] {
                        crIDNum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateCR(string crIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateCR", new object[] {
                        crIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndUpdateCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="UpdateCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/U" +
"pdateCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("UpdateCR2Result")]
        public ToolkitResultProtocol UpdateCR(UpdateCRSetupProtocol setupParam) {
            object[] results = this.Invoke("UpdateCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateCR1(UpdateCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndUpdateCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/F" +
"ixCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol FixCR(string crIDNum) {
            object[] results = this.Invoke("FixCR", new object[] {
                        crIDNum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFixCR(string crIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FixCR", new object[] {
                        crIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndFixCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="FixCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/F" +
"ixCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("FixCR2Result")]
        public ToolkitResultProtocol FixCR(FixCRSetupProtocol setupParam) {
            object[] results = this.Invoke("FixCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFixCR1(FixCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FixCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndFixCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/D" +
"uplicateCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol DuplicateCR(string crIDNum, string masterCRIDNum) {
            object[] results = this.Invoke("DuplicateCR", new object[] {
                        crIDNum,
                        masterCRIDNum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDuplicateCR(string crIDNum, string masterCRIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DuplicateCR", new object[] {
                        crIDNum,
                        masterCRIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndDuplicateCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="DuplicateCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/D" +
"uplicateCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("DuplicateCR2Result")]
        public ToolkitResultProtocol DuplicateCR(DuplicateCRSetupProtocol setupParam) {
            object[] results = this.Invoke("DuplicateCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDuplicateCR1(DuplicateCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DuplicateCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndDuplicateCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/A" +
"ddModuleToCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol AddModuleToCR(int fixObjid, string fileName) {
            object[] results = this.Invoke("AddModuleToCR", new object[] {
                        fixObjid,
                        fileName});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddModuleToCR(int fixObjid, string fileName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddModuleToCR", new object[] {
                        fixObjid,
                        fileName}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndAddModuleToCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="AddModuleToCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/A" +
"ddModuleToCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("AddModuleToCR2Result")]
        public ToolkitResultProtocol AddModuleToCR(AddModuleToCRSetupProtocol setupParam) {
            object[] results = this.Invoke("AddModuleToCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddModuleToCR1(AddModuleToCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddModuleToCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndAddModuleToCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/C" +
"hangeCRStatus", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol ChangeCRStatus(string crIDNum) {
            object[] results = this.Invoke("ChangeCRStatus", new object[] {
                        crIDNum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChangeCRStatus(string crIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChangeCRStatus", new object[] {
                        crIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndChangeCRStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="ChangeCRStatus1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/C" +
"hangeCRStatus2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("ChangeCRStatus2Result")]
        public ToolkitResultProtocol ChangeCRStatus(ChangeCRStatusSetupProtocol setupParam) {
            object[] results = this.Invoke("ChangeCRStatus1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChangeCRStatus1(ChangeCRStatusSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChangeCRStatus1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndChangeCRStatus1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/R" +
"eopenCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol ReopenCR(string crIDNum) {
            object[] results = this.Invoke("ReopenCR", new object[] {
                        crIDNum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReopenCR(string crIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReopenCR", new object[] {
                        crIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndReopenCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="ReopenCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/R" +
"eopenCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("ReopenCR2Result")]
        public ToolkitResultProtocol ReopenCR(ReopenCRSetupProtocol setupParam) {
            object[] results = this.Invoke("ReopenCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReopenCR1(ReopenCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReopenCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndReopenCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/C" +
"loseCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol CloseCR(string crIDNum) {
            object[] results = this.Invoke("CloseCR", new object[] {
                        crIDNum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCloseCR(string crIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CloseCR", new object[] {
                        crIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndCloseCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="CloseCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/C" +
"loseCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("CloseCR2Result")]
        public ToolkitResultProtocol CloseCR(CloseCRSetupProtocol setupParam) {
            object[] results = this.Invoke("CloseCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCloseCR1(CloseCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CloseCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndCloseCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/C" +
"heckClearQualityTransition", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol CheckClearQualityTransition(string oldCondition, string oldStatus, string newCondition, string newStatus, string userName) {
            object[] results = this.Invoke("CheckClearQualityTransition", new object[] {
                        oldCondition,
                        oldStatus,
                        newCondition,
                        newStatus,
                        userName});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckClearQualityTransition(string oldCondition, string oldStatus, string newCondition, string newStatus, string userName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckClearQualityTransition", new object[] {
                        oldCondition,
                        oldStatus,
                        newCondition,
                        newStatus,
                        userName}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndCheckClearQualityTransition(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="CheckClearQualityTransition1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/C" +
"heckClearQualityTransition2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("CheckClearQualityTransition2Result")]
        public ToolkitResultProtocol CheckClearQualityTransition(CheckClearQualityTransitionSetupProtocol setupParam) {
            object[] results = this.Invoke("CheckClearQualityTransition1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckClearQualityTransition1(CheckClearQualityTransitionSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckClearQualityTransition1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndCheckClearQualityTransition1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/L" +
"ogCRNote", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol LogCRNote(string crIDNum) {
            object[] results = this.Invoke("LogCRNote", new object[] {
                        crIDNum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogCRNote(string crIDNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LogCRNote", new object[] {
                        crIDNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndLogCRNote(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="LogCRNote1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/L" +
"ogCRNote2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("LogCRNote2Result")]
        public ToolkitResultProtocol LogCRNote(LogCRNoteSetupProtocol setupParam) {
            object[] results = this.Invoke("LogCRNote1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogCRNote1(LogCRNoteSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LogCRNote1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndLogCRNote1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/C" +
"reateCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol CreateCR(string partNumber, string partRevision, string partDomain) {
            object[] results = this.Invoke("CreateCR", new object[] {
                        partNumber,
                        partRevision,
                        partDomain});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateCR(string partNumber, string partRevision, string partDomain, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateCR", new object[] {
                        partNumber,
                        partRevision,
                        partDomain}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndCreateCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="CreateCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/C" +
"reateCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("CreateCR2Result")]
        public ToolkitResultProtocol CreateCR(CreateCRSetupProtocol setupParam) {
            object[] results = this.Invoke("CreateCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateCR1(CreateCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndCreateCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/Y" +
"ankCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol YankCR(string cridnum) {
            object[] results = this.Invoke("YankCR", new object[] {
                        cridnum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginYankCR(string cridnum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("YankCR", new object[] {
                        cridnum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndYankCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="YankCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/Y" +
"ankCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("YankCR2Result")]
        public ToolkitResultProtocol YankCR(YankCRSetupProtocol setupParam) {
            object[] results = this.Invoke("YankCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginYankCR1(YankCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("YankCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndYankCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/M" +
"oveCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol MoveCR(string cridnum, string newWipBin) {
            object[] results = this.Invoke("MoveCR", new object[] {
                        cridnum,
                        newWipBin});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMoveCR(string cridnum, string newWipBin, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("MoveCR", new object[] {
                        cridnum,
                        newWipBin}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndMoveCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="MoveCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/M" +
"oveCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("MoveCR2Result")]
        public ToolkitResultProtocol MoveCR(MoveCRSetupProtocol setupParam) {
            object[] results = this.Invoke("MoveCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMoveCR1(MoveCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("MoveCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndMoveCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/A" +
"ssignCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol AssignCR(string cridnum) {
            object[] results = this.Invoke("AssignCR", new object[] {
                        cridnum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAssignCR(string cridnum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AssignCR", new object[] {
                        cridnum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndAssignCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="AssignCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/A" +
"ssignCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("AssignCR2Result")]
        public ToolkitResultProtocol AssignCR(AssignCRSetupProtocol setupParam) {
            object[] results = this.Invoke("AssignCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAssignCR1(AssignCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AssignCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndAssignCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/F" +
"orwardCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol ForwardCR(string cridnum, string newQueue) {
            object[] results = this.Invoke("ForwardCR", new object[] {
                        cridnum,
                        newQueue});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginForwardCR(string cridnum, string newQueue, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ForwardCR", new object[] {
                        cridnum,
                        newQueue}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndForwardCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="ForwardCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/F" +
"orwardCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("ForwardCR2Result")]
        public ToolkitResultProtocol ForwardCR(ForwardCRSetupProtocol setupParam) {
            object[] results = this.Invoke("ForwardCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginForwardCR1(ForwardCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ForwardCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndForwardCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/R" +
"ejectCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol RejectCR(string cridnum) {
            object[] results = this.Invoke("RejectCR", new object[] {
                        cridnum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRejectCR(string cridnum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RejectCR", new object[] {
                        cridnum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndRejectCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="RejectCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/R" +
"ejectCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("RejectCR2Result")]
        public ToolkitResultProtocol RejectCR(RejectCRSetupProtocol setupParam) {
            object[] results = this.Invoke("RejectCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRejectCR1(RejectCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RejectCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndRejectCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/A" +
"cceptCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol AcceptCR(string cridnum) {
            object[] results = this.Invoke("AcceptCR", new object[] {
                        cridnum});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAcceptCR(string cridnum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AcceptCR", new object[] {
                        cridnum}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndAcceptCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="AcceptCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/A" +
"cceptCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("AcceptCR2Result")]
        public ToolkitResultProtocol AcceptCR(AcceptCRSetupProtocol setupParam) {
            object[] results = this.Invoke("AcceptCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAcceptCR1(AcceptCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AcceptCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndAcceptCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/D" +
"ispatchCR", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        public ToolkitResultProtocol DispatchCR(string cridnum, string queue) {
            object[] results = this.Invoke("DispatchCR", new object[] {
                        cridnum,
                        queue});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDispatchCR(string cridnum, string queue, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DispatchCR", new object[] {
                        cridnum,
                        queue}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndDispatchCR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="DispatchCR1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1/D" +
"ispatchCR2", RequestNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1", ResponseNamespace="http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("DispatchCR2Result")]
        public ToolkitResultProtocol DispatchCR(DispatchCRSetupProtocol setupParam) {
            object[] results = this.Invoke("DispatchCR1", new object[] {
                        setupParam});
            return ((ToolkitResultProtocol)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDispatchCR1(DispatchCRSetupProtocol setupParam, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DispatchCR1", new object[] {
                        setupParam}, callback, asyncState);
        }
        
        /// <remarks/>
        public ToolkitResultProtocol EndDispatchCR1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ToolkitResultProtocol)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("AuthenticationHeader", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class AuthenticationHeader : SoapHeader {
        
        /// <remarks/>
        public string SessionID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("DispatchCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class DispatchCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string Queue;
        
        /// <remarks/>
        public System.DateTime DispatchDate;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("AcceptCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class AcceptCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public System.DateTime AcceptDate;
        
        /// <remarks/>
        public string WipBin;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RejectCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class RejectCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public System.DateTime RejectDate;
        
        /// <remarks/>
        public string WipBin;
        
        /// <remarks/>
        public string Notes;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("ForwardCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class ForwardCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string NewQueue;
        
        /// <remarks/>
        public System.DateTime ForwardDate;
        
        /// <remarks/>
        public string Notes;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("AssignCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class AssignCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string NewUser;
        
        /// <remarks/>
        public string WipBin;
        
        /// <remarks/>
        public System.DateTime AssignDate;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("MoveCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class MoveCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string NewWipBin;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("YankCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class YankCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string WipBin;
        
        /// <remarks/>
        public System.DateTime YankDate;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("CreateCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class CreateCRSetupProtocol {
        
        /// <remarks/>
        public string PartNumber;
        
        /// <remarks/>
        public string PartRevision;
        
        /// <remarks/>
        public string PartDomain;
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Status;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string CRType;
        
        /// <remarks/>
        public string Priority;
        
        /// <remarks/>
        public string Frequency;
        
        /// <remarks/>
        public string FoundOnCPU;
        
        /// <remarks/>
        public string OperatingSystem;
        
        /// <remarks/>
        public string Memory;
        
        /// <remarks/>
        public string CRClass;
        
        /// <remarks/>
        public string IntroductionPhase;
        
        /// <remarks/>
        public string TestClass;
        
        /// <remarks/>
        public string FixedIn;
        
        /// <remarks/>
        public string VerificationTest;
        
        /// <remarks/>
        public string Queue;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public System.DateTime CreateDate;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public AdditionalFieldProtocol[] AdditionalFields;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("AdditionalFieldProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class AdditionalFieldProtocol {
        
        /// <remarks/>
        public string FieldName;
        
        /// <remarks/>
        public AdditionalFieldType FieldType;
        
        /// <remarks/>
        public string FieldValue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("AdditionalFieldType", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public enum AdditionalFieldType {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Long,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Date,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("LogCRNoteSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class LogCRNoteSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string Notes;
        
        /// <remarks/>
        public string InternalUseOnlyNotes;
        
        /// <remarks/>
        public System.DateTime LogDate;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public AdditionalFieldProtocol[] AdditionalFields;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("CheckClearQualityTransitionSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class CheckClearQualityTransitionSetupProtocol {
        
        /// <remarks/>
        public string OldCondition;
        
        /// <remarks/>
        public string OldStatus;
        
        /// <remarks/>
        public string NewCondition;
        
        /// <remarks/>
        public string NewStatus;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("CloseCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class CloseCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string Status;
        
        /// <remarks/>
        public string Notes;
        
        /// <remarks/>
        public string TestCase;
        
        /// <remarks/>
        public string FixedInRelease;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public System.DateTime CloseDate;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public AdditionalFieldProtocol[] AdditionalFields;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("ReopenCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class ReopenCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string Status;
        
        /// <remarks/>
        public string WipBin;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public System.DateTime ReopenDate;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("ChangeCRStatusSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class ChangeCRStatusSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string NewStatus;
        
        /// <remarks/>
        public System.DateTime ChangeDate;
        
        /// <remarks/>
        public string Notes;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("AddModuleToCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class AddModuleToCRSetupProtocol {
        
        /// <remarks/>
        public int FixObjid;
        
        /// <remarks/>
        public string FileName;
        
        /// <remarks/>
        public string FileRevision;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("DuplicateCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class DuplicateCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string Status;
        
        /// <remarks/>
        public string MasterCRIDNum;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public System.DateTime CloseDate;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("FixCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class FixCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string Status;
        
        /// <remarks/>
        public string Notes;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public System.DateTime FixDate;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public AdditionalFieldProtocol[] AdditionalFields;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("UpdateCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class UpdateCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string PartNumber;
        
        /// <remarks/>
        public string PartRevision;
        
        /// <remarks/>
        public string PartDomain;
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string CRType;
        
        /// <remarks/>
        public string Priority;
        
        /// <remarks/>
        public string Frequency;
        
        /// <remarks/>
        public string FoundOnCPU;
        
        /// <remarks/>
        public string OperatingSystem;
        
        /// <remarks/>
        public string Memory;
        
        /// <remarks/>
        public string CRClass;
        
        /// <remarks/>
        public string IntroductionPhase;
        
        /// <remarks/>
        public string TestClass;
        
        /// <remarks/>
        public string FixedIn;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public System.DateTime UpdateDate;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public AdditionalFieldProtocol[] AdditionalFields;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("ReplicateCRSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class ReplicateCRSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public System.DateTime ReplicatedDate;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("LogCREmailSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class LogCREmailSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public System.DateTime LogDate;
        
        /// <remarks/>
        public string Message;
        
        /// <remarks/>
        public string Recipient;
        
        /// <remarks/>
        public string CCList;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public bool SendEmail;
        
        /// <remarks/>
        public AdditionalFieldProtocol[] AdditionalFields;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("FixFailedSetupProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class FixFailedSetupProtocol {
        
        /// <remarks/>
        public string CRIDNum;
        
        /// <remarks/>
        public string Status;
        
        /// <remarks/>
        public string Notes;
        
        /// <remarks/>
        public string TestCase;
        
        /// <remarks/>
        public string FixedInRelease;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public System.DateTime FailedDate;
        
        /// <remarks/>
        public bool GenerateTimeBombs;
        
        /// <remarks/>
        public AdditionalFieldProtocol[] AdditionalFields;
        
        /// <remarks/>
        public int DirtyFieldFlags;
        
        /// <remarks/>
        public int ConstructorCue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("ToolkitResultProtocol", "http://www.fchoice.com/schemas/FChoice.WebServices.Clarify.QualityToolkitSrv_v1")]
    public class ToolkitResultProtocol {
        
        /// <remarks/>
        public short ReturnCode;
        
        /// <remarks/>
        public string IDNum;
        
        /// <remarks/>
        public int Objid;
    }
}
