//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Web;
using System.Web.Services;
using Protocol = FChoice.WebServices.Clarify.Client.Protocols.FieldOpsToolkitSrv;
using FChoice.WebServices.Clarify.Client;

namespace FChoice.WebServices.Clarify.Client.FieldOps
{
	public class FieldOpsToolkitWS
	{
		private Protocol.FieldOpsToolkitSrv toolkitProtocol;
		
		public FieldOpsToolkitWS(ClarifySessionWS session)
		{
			toolkitProtocol = new Protocol.FieldOpsToolkitSrv();
			toolkitProtocol.Url = new Uri( session.BaseUri, "FieldOpsToolkitSrv.asmx" ).ToString();
			toolkitProtocol.AuthenticationHeaderValue = new Protocol.AuthenticationHeader();
			
			toolkitProtocol.AuthenticationHeaderValue.SessionID = session.SessionToken;
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedExchange(String partRequestDetailIDNum, Int32 removeSitePartObjid, String installPartNumber, String installPartRevision, String installPartDomain, String installSerialNumber)
		{
			return toolkitProtocol.LogPartsUsedExchange( partRequestDetailIDNum, removeSitePartObjid, installPartNumber, installPartRevision, installPartDomain, installSerialNumber );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedExchange(String partRequestDetailIDNum, Int32 removeSitePartObjid, String installPartNumber, String installPartRevision, String installPartDomain, Int32 installQuantity)
		{
			return toolkitProtocol.LogPartsUsedExchange( partRequestDetailIDNum, removeSitePartObjid, installPartNumber, installPartRevision, installPartDomain, installQuantity );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedExchange(String partRequestDetailIDNum, String caseIDNum, Int32 removeSitePartObjid, String installPartNumber, String installPartRevision, String installPartDomain, String installSerialNumber)
		{
			return toolkitProtocol.LogPartsUsedExchange( partRequestDetailIDNum, caseIDNum, removeSitePartObjid, installPartNumber, installPartRevision, installPartDomain, installSerialNumber );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedExchange(String partRequestDetailIDNum, String caseIDNum, Int32 removeSitePartObjid, String installPartNumber, String installPartRevision, String installPartDomain, Int32 installQuantity)
		{
			return toolkitProtocol.LogPartsUsedExchange( partRequestDetailIDNum, caseIDNum, removeSitePartObjid, installPartNumber, installPartRevision, installPartDomain, installQuantity );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedExchange(LogPartsUsedExchangeSetupWS setupParam)
		{
			return toolkitProtocol.LogPartsUsedExchange( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedConsume(String partRequestDetailIDNum, String installPartNumber, String installPartRevision, String installPartDomain, String installSerialNumber)
		{
			return toolkitProtocol.LogPartsUsedConsume( partRequestDetailIDNum, installPartNumber, installPartRevision, installPartDomain, installSerialNumber );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedConsume(String partRequestDetailIDNum, String installPartNumber, String installPartRevision, String installPartDomain, Int32 installQuantity)
		{
			return toolkitProtocol.LogPartsUsedConsume( partRequestDetailIDNum, installPartNumber, installPartRevision, installPartDomain, installQuantity );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedConsume(String partRequestDetailIDNum, String caseIDNum, String installPartNumber, String installPartRevision, String installPartDomain, String installSerialNumber)
		{
			return toolkitProtocol.LogPartsUsedConsume( partRequestDetailIDNum, caseIDNum, installPartNumber, installPartRevision, installPartDomain, installSerialNumber );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedConsume(String partRequestDetailIDNum, String caseIDNum, String installPartNumber, String installPartRevision, String installPartDomain, Int32 installQuantity)
		{
			return toolkitProtocol.LogPartsUsedConsume( partRequestDetailIDNum, caseIDNum, installPartNumber, installPartRevision, installPartDomain, installQuantity );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedConsume(LogPartsUsedConsumeSetupWS setupParam)
		{
			return toolkitProtocol.LogPartsUsedConsume( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedInstall(String partRequestDetailIDNum, String installPartNumber, String installPartRevision, String installPartDomain, String installSerialNumber)
		{
			return toolkitProtocol.LogPartsUsedInstall( partRequestDetailIDNum, installPartNumber, installPartRevision, installPartDomain, installSerialNumber );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedInstall(String partRequestDetailIDNum, String installPartNumber, String installPartRevision, String installPartDomain, Int32 installQuantity)
		{
			return toolkitProtocol.LogPartsUsedInstall( partRequestDetailIDNum, installPartNumber, installPartRevision, installPartDomain, installQuantity );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedInstall(String partRequestDetailIDNum, String caseIDNum, String installPartNumber, String installPartRevision, String installPartDomain, String installSerialNumber)
		{
			return toolkitProtocol.LogPartsUsedInstall( partRequestDetailIDNum, caseIDNum, installPartNumber, installPartRevision, installPartDomain, installSerialNumber );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedInstall(String partRequestDetailIDNum, String caseIDNum, String installPartNumber, String installPartRevision, String installPartDomain, Int32 installQuantity)
		{
			return toolkitProtocol.LogPartsUsedInstall( partRequestDetailIDNum, caseIDNum, installPartNumber, installPartRevision, installPartDomain, installQuantity );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedInstall(LogPartsUsedInstallSetupWS setupParam)
		{
			return toolkitProtocol.LogPartsUsedInstall( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedRemove(String partRequestDetailIDNum, Int32 removeSitePartObjid)
		{
			return toolkitProtocol.LogPartsUsedRemove( partRequestDetailIDNum, removeSitePartObjid );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedRemove(String partRequestDetailIDNum, String caseIDNum, Int32 removeSitePartObjid)
		{
			return toolkitProtocol.LogPartsUsedRemove( partRequestDetailIDNum, caseIDNum, removeSitePartObjid );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedRemove(LogPartsUsedRemoveSetupWS setupParam)
		{
			return toolkitProtocol.LogPartsUsedRemove( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedUpgrade(String partRequestDetailIDNum, Int32 removeSitePartObjid, String installPartNumber, String installPartRevision, String installPartDomain, String installSerialNumber)
		{
			return toolkitProtocol.LogPartsUsedUpgrade( partRequestDetailIDNum, removeSitePartObjid, installPartNumber, installPartRevision, installPartDomain, installSerialNumber );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedUpgrade(String partRequestDetailIDNum, Int32 removeSitePartObjid, String installPartNumber, String installPartRevision, String installPartDomain, Int32 installQuantity)
		{
			return toolkitProtocol.LogPartsUsedUpgrade( partRequestDetailIDNum, removeSitePartObjid, installPartNumber, installPartRevision, installPartDomain, installQuantity );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedUpgrade(String partRequestDetailIDNum, String caseIDNum, Int32 removeSitePartObjid, String installPartNumber, String installPartRevision, String installPartDomain, String installSerialNumber)
		{
			return toolkitProtocol.LogPartsUsedUpgrade( partRequestDetailIDNum, caseIDNum, removeSitePartObjid, installPartNumber, installPartRevision, installPartDomain, installSerialNumber );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedUpgrade(String partRequestDetailIDNum, String caseIDNum, Int32 removeSitePartObjid, String installPartNumber, String installPartRevision, String installPartDomain, Int32 installQuantity)
		{
			return toolkitProtocol.LogPartsUsedUpgrade( partRequestDetailIDNum, caseIDNum, removeSitePartObjid, installPartNumber, installPartRevision, installPartDomain, installQuantity );
		}
		
		public Protocol.ToolkitResultProtocol LogPartsUsedUpgrade(LogPartsUsedUpgradeSetupWS setupParam)
		{
			return toolkitProtocol.LogPartsUsedUpgrade( setupParam.ToProtocol() );
		}
		
		public Protocol.PartTransferResultProtocol PartTransfer(String partNumber, String partRevision, String partDomain, Int32 quantity, Protocol.LocationProtocol fromlocation, Protocol.LocationProtocol tolocation)
		{
			return toolkitProtocol.PartTransfer( partNumber, partRevision, partDomain, quantity, fromlocation, tolocation );
		}
		
		public Protocol.PartTransferResultProtocol PartTransfer(String partNumber, String partRevision, String partDomain, String serialNumber, Protocol.LocationProtocol fromlocation, Protocol.LocationProtocol tolocation)
		{
			return toolkitProtocol.PartTransfer( partNumber, partRevision, partDomain, serialNumber, fromlocation, tolocation );
		}
		
		public Protocol.PartTransferResultProtocol PartTransfer(PartTransferSetupWS setupParam)
		{
			return toolkitProtocol.PartTransfer( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol MoveSitePartToBin(Int32 sitePartObjid, Int32 parentBinObjid)
		{
			return toolkitProtocol.MoveSitePartToBin( sitePartObjid, parentBinObjid );
		}
		
		public Protocol.ToolkitResultProtocol MoveSitePartToBin(MoveSitePartToBinSetupWS setupParam)
		{
			return toolkitProtocol.MoveSitePartToBin( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol MoveSitePartToSite(Int32 sitePartObjid, String siteIDNum)
		{
			return toolkitProtocol.MoveSitePartToSite( sitePartObjid, siteIDNum );
		}
		
		public Protocol.ToolkitResultProtocol MoveSitePartToSite(MoveSitePartToSiteSetupWS setupParam)
		{
			return toolkitProtocol.MoveSitePartToSite( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol MoveSitePartToPart(Int32 sitePartObjid, Int32 parentSitePartObjid)
		{
			return toolkitProtocol.MoveSitePartToPart( sitePartObjid, parentSitePartObjid );
		}
		
		public Protocol.ToolkitResultProtocol MoveSitePartToPart(MoveSitePartToPartSetupWS setupParam)
		{
			return toolkitProtocol.MoveSitePartToPart( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol ReinstallSitePart(Int32 sitePartObjid, String siteIDNum)
		{
			return toolkitProtocol.ReinstallSitePart( sitePartObjid, siteIDNum );
		}
		
		public Protocol.ToolkitResultProtocol ReinstallSitePart(ReinstallSitePartSetupWS setupParam)
		{
			return toolkitProtocol.ReinstallSitePart( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DeinstallSitePart(Int32 sitePartObjid)
		{
			return toolkitProtocol.DeinstallSitePart( sitePartObjid );
		}
		
		public Protocol.ToolkitResultProtocol DeinstallSitePart(DeinstallSitePartSetupWS setupParam)
		{
			return toolkitProtocol.DeinstallSitePart( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateSitePart(Int32 sitePartObjid)
		{
			return toolkitProtocol.UpdateSitePart( sitePartObjid );
		}
		
		public Protocol.ToolkitResultProtocol UpdateSitePart(UpdateSitePartSetupWS setupParam)
		{
			return toolkitProtocol.UpdateSitePart( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol InstallSitePart(String siteIDNum, String partNumber, String partrevision, String partdomain, Int32 quantity)
		{
			return toolkitProtocol.InstallSitePart( siteIDNum, partNumber, partrevision, partdomain, quantity );
		}
		
		public Protocol.ToolkitResultProtocol InstallSitePart(String siteIDNum, String partNumber, String partrevision, String partdomain, String serialNumber)
		{
			return toolkitProtocol.InstallSitePart( siteIDNum, partNumber, partrevision, partdomain, serialNumber );
		}
		
		public Protocol.ToolkitResultProtocol InstallSitePart(InstallSitePartSetupWS setupParam)
		{
			return toolkitProtocol.InstallSitePart( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DeleteServiceInterruption(Int32 appointmentObjid)
		{
			return toolkitProtocol.DeleteServiceInterruption( appointmentObjid );
		}
		
		public Protocol.ToolkitResultProtocol DeleteServiceInterruption(DeleteServiceInterruptionSetupWS setupParam)
		{
			return toolkitProtocol.DeleteServiceInterruption( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateServiceInterruption(Int32 appointmentObjid)
		{
			return toolkitProtocol.UpdateServiceInterruption( appointmentObjid );
		}
		
		public Protocol.ToolkitResultProtocol UpdateServiceInterruption(UpdateServiceInterruptionSetupWS setupParam)
		{
			return toolkitProtocol.UpdateServiceInterruption( setupParam.ToProtocol() );
		}
		
		public Protocol.AddServiceInterruptionResultProtocol AddServiceInterruption(String caseIDNum)
		{
			return toolkitProtocol.AddServiceInterruption( caseIDNum );
		}
		
		public Protocol.AddServiceInterruptionResultProtocol AddServiceInterruption(AddServiceInterruptionSetupWS setupParam)
		{
			return toolkitProtocol.AddServiceInterruption( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DeleteExpenseLog(Int32 expenseLogObjid)
		{
			return toolkitProtocol.DeleteExpenseLog( expenseLogObjid );
		}
		
		public Protocol.ToolkitResultProtocol DeleteExpenseLog(DeleteExpenseLogSetupWS setupParam)
		{
			return toolkitProtocol.DeleteExpenseLog( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateExpenseLog(Int32 expenseLogObjid, Double quantity, Double rate)
		{
			return toolkitProtocol.UpdateExpenseLog( expenseLogObjid, quantity, rate );
		}
		
		public Protocol.ToolkitResultProtocol UpdateExpenseLog(UpdateExpenseLogSetupWS setupParam)
		{
			return toolkitProtocol.UpdateExpenseLog( setupParam.ToProtocol() );
		}
		
		public Protocol.CreateExpenseLogResultProtocol CreateExpenseLog(Int32 onsiteLogObjid)
		{
			return toolkitProtocol.CreateExpenseLog( onsiteLogObjid );
		}
		
		public Protocol.CreateExpenseLogResultProtocol CreateExpenseLog(CreateExpenseLogSetupWS setupParam)
		{
			return toolkitProtocol.CreateExpenseLog( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DeleteTimeLog(Int32 timeLogObjid)
		{
			return toolkitProtocol.DeleteTimeLog( timeLogObjid );
		}
		
		public Protocol.ToolkitResultProtocol DeleteTimeLog(DeleteTimeLogSetupWS setupParam)
		{
			return toolkitProtocol.DeleteTimeLog( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateTimeLog(Int32 timeLogObjid)
		{
			return toolkitProtocol.UpdateTimeLog( timeLogObjid );
		}
		
		public Protocol.ToolkitResultProtocol UpdateTimeLog(UpdateTimeLogSetupWS setupParam)
		{
			return toolkitProtocol.UpdateTimeLog( setupParam.ToProtocol() );
		}
		
		public Protocol.CreateTimeLogResultProtocol CreateTimeLog(Int32 onsiteLogObjid, DateTime startDate, System.Int32 duration)
		{
			return toolkitProtocol.CreateTimeLog( onsiteLogObjid, startDate, duration );
		}
		
		public Protocol.CreateTimeLogResultProtocol CreateTimeLog(CreateTimeLogSetupWS setupParam)
		{
			return toolkitProtocol.CreateTimeLog( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DeleteOnsiteLog(Int32 onsiteLogObjid)
		{
			return toolkitProtocol.DeleteOnsiteLog( onsiteLogObjid );
		}
		
		public Protocol.ToolkitResultProtocol DeleteOnsiteLog(DeleteOnsiteLogSetupWS setupParam)
		{
			return toolkitProtocol.DeleteOnsiteLog( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol CreateOnsiteLog(Protocol.CaseObjectType objectType, String objectIDNum)
		{
			return toolkitProtocol.CreateOnsiteLog( objectType, objectIDNum );
		}
		
		public Protocol.ToolkitResultProtocol CreateOnsiteLog(CreateOnsiteLogSetupWS setupParam)
		{
			return toolkitProtocol.CreateOnsiteLog( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DeleteAppointment(Int32 appointmentObjid)
		{
			return toolkitProtocol.DeleteAppointment( appointmentObjid );
		}
		
		public Protocol.ToolkitResultProtocol DeleteAppointment(DeleteAppointmentSetupWS setupParam)
		{
			return toolkitProtocol.DeleteAppointment( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol UpdateAppointment(Int32 appointmentObjid)
		{
			return toolkitProtocol.UpdateAppointment( appointmentObjid );
		}
		
		public Protocol.ToolkitResultProtocol UpdateAppointment(UpdateAppointmentSetupWS setupParam)
		{
			return toolkitProtocol.UpdateAppointment( setupParam.ToProtocol() );
		}
		
		public Protocol.CreateAppointmentResultProtocol CreateAppointment(DateTime startDate, DateTime endDate)
		{
			return toolkitProtocol.CreateAppointment( startDate, endDate );
		}
		
		public Protocol.CreateAppointmentResultProtocol CreateAppointment(DateTime startDate, System.Int32 duration)
		{
			return toolkitProtocol.CreateAppointment( startDate, duration );
		}
		
		public Protocol.CreateAppointmentResultProtocol CreateAppointment(System.Int32 duration, DateTime endDate)
		{
			return toolkitProtocol.CreateAppointment( duration, endDate );
		}
		
		public Protocol.CreateAppointmentResultProtocol CreateAppointment(CreateAppointmentSetupWS setupParam)
		{
			return toolkitProtocol.CreateAppointment( setupParam.ToProtocol() );
		}
		
		public Protocol.ToolkitResultProtocol DispatchFieldEngineer(String caseIDNum)
		{
			return toolkitProtocol.DispatchFieldEngineer( caseIDNum );
		}
		
		public Protocol.ToolkitResultProtocol DispatchFieldEngineer(DispatchFieldEngineerSetupWS setupParam)
		{
			return toolkitProtocol.DispatchFieldEngineer( setupParam.ToProtocol() );
		}
		
	}
}
