//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web;
using System.Web.Services;

using FChoice.Toolkits.Clarify;
using FChoice.WebServices.Clarify;

namespace FChoice.WebServices.Clarify.Protocols.Interfaces
{
	[Serializable]
	public class MoveSitePartToSiteSetupProtocol
	{
		public MoveSitePartToSiteSetupProtocol(){}

		public System.Int32 SitePartObjid;
		public System.DateTime MoveDate;
		public System.String ParentSiteIDNum;
		public System.Boolean AddActivityLog;
		public System.String UserName;
		public System.Boolean InstallAndMove;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class MoveSitePartToBinSetupProtocol
	{
		public MoveSitePartToBinSetupProtocol(){}

		public System.Int32 SitePartObjid;
		public System.DateTime MoveDate;
		public System.Int32 ParentBinObjid;
		public System.Boolean AddActivityLog;
		public System.String UserName;
		public System.Boolean InstallAndMove;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class MoveSitePartToPartSetupProtocol
	{
		public MoveSitePartToPartSetupProtocol(){}

		public System.Int32 SitePartObjid;
		public System.DateTime MoveDate;
		public System.Int32 ParentSitePartObjid;
		public System.Boolean AddActivityLog;
		public System.String UserName;
		public System.Boolean InstallAndMove;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ReinstallSitePartToPartSetupProtocol
	{
		public ReinstallSitePartToPartSetupProtocol(){}

		public System.Int32 SitePartObjid;
		public System.String SiteIDNum;
		public System.Int32 ParentSitePartObjid;
		public System.String UserName;
		public System.DateTime ReinstallDate;
		public System.Boolean AddActivityLog;
		public System.Boolean UseInstall;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ReinstallSitePartToBinSetupProtocol
	{
		public ReinstallSitePartToBinSetupProtocol(){}

		public System.Int32 SitePartObjid;
		public System.String SiteIDNum;
		public System.Int32 ParentBinObjid;
		public System.String UserName;
		public System.DateTime ReinstallDate;
		public System.Boolean AddActivityLog;
		public System.Boolean UseInstall;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ReinstallSitePartToSiteSetupProtocol
	{
		public ReinstallSitePartToSiteSetupProtocol(){}

		public System.Int32 SitePartObjid;
		public System.String SiteIDNum;
		public System.String UserName;
		public System.DateTime ReinstallDate;
		public System.Boolean AddActivityLog;
		public System.Boolean UseInstall;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateProductBinSetupProtocol
	{
		public CreateProductBinSetupProtocol(){}

		public System.String BinName;
		public System.String SiteIDNum;
		public System.Int32 ParentBinObjid;
		public System.String Description;
		public System.Int32 PrimarySupportEmployeeObjid;
		public System.Int32 SecondarySupportEmployeeObjid;
		public System.String UserName;
		public System.DateTime CreateDate;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateProductBinSetupProtocol
	{
		public UpdateProductBinSetupProtocol(){}

		public System.Int32 BinObjid;
		public System.String BinName;
		public System.String Description;
		public System.Int32 PrimarySupportEmployeeObjid;
		public System.Int32 SecondarySupportEmployeeObjid;
		public System.String UserName;
		public System.DateTime UpdateDate;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DeleteProductBinSetupProtocol
	{
		public DeleteProductBinSetupProtocol(){}

		public System.Int32 BinObjid;
		public System.String UserName;
		public System.DateTime DeleteDate;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DeinstallSitePartSetupProtocol
	{
		public DeinstallSitePartSetupProtocol(){}

		public System.Int32 SitePartObjid;
		public System.String UserName;
		public System.DateTime DeinstallDate;
		public System.Boolean UseRemove;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateInteractionSetupProtocol
	{
		public CreateInteractionSetupProtocol(){}

		public System.String Title;
		public System.String Notes;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String ZipCode;
		public System.String Reason1;
		public System.String Reason2;
		public System.String ProductName;
		public System.String Direction;
		public System.String InteractionType;
		public System.String Origin;
		public System.Boolean IsDoneInOne;
		public System.String Result;
		public System.Boolean FeeBased;
		public System.String PayOption;
		public System.String LeadSource;
		public System.DateTime StartDate;
		public System.Int32 Duration;
		public System.Int32 WaitDuration;
		public System.Int32 EnteredDuration;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateEmployeeSetupProtocol
	{
		public CreateEmployeeSetupProtocol(){}

		public System.String FirstName;
		public System.String LastName;
		public System.String LoginName;
		public System.String Password;
		public System.String SiteIDNum;
		public System.String Email;
		public System.String Phone;
		public System.String Pager;
		public System.String OnlinePrivilegeClass;
		public System.String OfflinePrivilegeClass;
		public System.String EmployeeIdentifier;
		public System.Boolean IsActive;
		public System.Boolean AllowProxy;
		public System.DateTime StartDate;
		public System.String Supervisor;
		public System.String WorkGroup;
		public System.DateTime WorkGroupStartDate;
		public System.Double LaborRate;
		public System.Boolean IsSupervisor;
		public System.Boolean IsFieldEngineer;
		public System.String NormalBusinessHoursHigh;
		public System.String NormalBusinessHoursMed;
		public System.String NormalBusinessHoursLow;
		public System.String AfterBusinessHoursHigh;
		public System.String AfterBusinessHoursMed;
		public System.String AfterBusinessHoursLow;
		public System.String DefaultWipBinTitle;
		public System.String ResourceConfig;
		public System.String DefaultTablespace;
		public System.String TempTablespace;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class YankSolutionSetupProtocol
	{
		public YankSolutionSetupProtocol(){}

		public System.String SolutionIDNum;
		public System.String WipBin;
		public System.DateTime YankDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class RejectSolutionSetupProtocol
	{
		public RejectSolutionSetupProtocol(){}

		public System.String SolutionIDNum;
		public System.DateTime RejectDate;
		public System.String WipBin;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class MoveSolutionSetupProtocol
	{
		public MoveSolutionSetupProtocol(){}

		public System.String SolutionIDNum;
		public System.String NewWipBin;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ForwardSolutionSetupProtocol
	{
		public ForwardSolutionSetupProtocol(){}

		public System.String SolutionIDNum;
		public System.String NewQueue;
		public System.DateTime ForwardDate;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DispatchSolutionSetupProtocol
	{
		public DispatchSolutionSetupProtocol(){}

		public System.String SolutionIDNum;
		public System.String Queue;
		public System.DateTime DispatchDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AssignSolutionSetupProtocol
	{
		public AssignSolutionSetupProtocol(){}

		public System.String SolutionIDNum;
		public System.String NewUser;
		public System.String WipBin;
		public System.DateTime AssignDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AcceptSolutionSetupProtocol
	{
		public AcceptSolutionSetupProtocol(){}

		public System.String SolutionIDNum;
		public System.DateTime AcceptDate;
		public System.String WipBin;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateSitePartSetupProtocol
	{
		public UpdateSitePartSetupProtocol(){}

		public System.Int32 SitePartObjid;
		public System.String InstanceName;
		public System.String SerialNumber;
		public System.String InvoiceNumber;
		public System.DateTime ShipDate;
		public System.DateTime InstallDate;
		public System.DateTime WarrantyDate;
		public System.Int32 Quantity;
		public System.String PartStatus;
		public System.String Comments;
		public System.DateTime ServiceEndDate;
		public System.String UserName;
		public System.String PartRevision;
		public System.Boolean AddActivityLog;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class InstallSitePartToPartSetupProtocol
	{
		public InstallSitePartToPartSetupProtocol(){}

		public System.String SiteIDNum;
		public System.String PartNumber;
		public System.String PartRevision;
		public System.String PartDomain;
		public System.Int32 Quantity;
		public System.String SerialNumber;
		public System.Int32 ParentSitePartObjid;
		public System.String InstanceName;
		public System.String Comments;
		public System.String PartStatus;
		public System.String InvoiceNumber;
		public System.String UserName;
		public System.DateTime InstallDate;
		public System.DateTime ShipDate;
		public System.Boolean AddActivityLog;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class InstallSitePartToBinSetupProtocol
	{
		public InstallSitePartToBinSetupProtocol(){}

		public System.String SiteIDNum;
		public System.String PartNumber;
		public System.String PartRevision;
		public System.String PartDomain;
		public System.Int32 Quantity;
		public System.String SerialNumber;
		public System.Int32 ParentBinObjid;
		public System.String InstanceName;
		public System.String Comments;
		public System.String PartStatus;
		public System.String InvoiceNumber;
		public System.String UserName;
		public System.DateTime InstallDate;
		public System.DateTime ShipDate;
		public System.Boolean AddActivityLog;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class InstallSitePartToSiteSetupProtocol
	{
		public InstallSitePartToSiteSetupProtocol(){}

		public System.String SiteIDNum;
		public System.String PartNumber;
		public System.String PartRevision;
		public System.String PartDomain;
		public System.Int32 Quantity;
		public System.String SerialNumber;
		public System.String InstanceName;
		public System.String Comments;
		public System.String PartStatus;
		public System.String InvoiceNumber;
		public System.String UserName;
		public System.DateTime InstallDate;
		public System.DateTime ShipDate;
		public System.Boolean AddActivityLog;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddContactToContractSetupProtocol
	{
		public AddContactToContractSetupProtocol(){}

		public System.String ContractIDNum;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String SiteIDNum;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddSitePartToContractSetupProtocol
	{
		public AddSitePartToContractSetupProtocol(){}

		public System.String ContractIDNum;
		public System.String SiteIDNum;
		public System.Int32 SitePartObjid;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddSiteToContractSetupProtocol
	{
		public AddSiteToContractSetupProtocol(){}

		public System.String ContractIDNum;
		public System.String SiteIDNum;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateContractSetupProtocol
	{
		public CreateContractSetupProtocol(){}

		public System.String ContractType;
		public System.String Status;
		public System.String PONumber;
		public System.String PayOptions;
		public System.Int32 PhoneResponseDuration;
		public System.Int32 OnsiteResponseDuration;
		public System.String BusinessHoursForPM;
		public System.DateTime StartDate;
		public System.DateTime ExpireDate;
		public System.String UnitType;
		public System.Double UnitsPurchased;
		public System.Double UnitsUsed;
		public System.Double UnitsAvailable;
		public System.Boolean UseSpecialConsiderations;
		public System.String Notes;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateContractSetupProtocol
	{
		public UpdateContractSetupProtocol(){}

		public System.String ContractIDNum;
		public System.String ContractType;
		public System.String Status;
		public System.String PONumber;
		public System.String PayOptions;
		public System.Int32 PhoneResponseDuration;
		public System.Int32 OnsiteResponseDuration;
		public System.String BusinessHoursForPM;
		public System.DateTime StartDate;
		public System.DateTime ExpireDate;
		public System.String UnitType;
		public System.Double UnitsPurchased;
		public System.Double UnitsUsed;
		public System.Double UnitsAvailable;
		public System.Boolean UseSpecialConsiderations;
		public System.String Notes;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdatePartRevisionSetupProtocol
	{
		public UpdatePartRevisionSetupProtocol(){}

		public System.String PartNumber;
		public System.String PartDomain;
		public System.String PartRevision;
		public System.String ReplacePartNumber;
		public System.String ReplacePartDomain;
		public System.String ReplacePartRevision;
		public System.DateTime ReplaceDate;
		public FChoice.Toolkits.Clarify.PartRevisionStatus Status;
		public System.String NewPartRevision;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreatePartRevisionSetupProtocol
	{
		public CreatePartRevisionSetupProtocol(){}

		public System.String PartNumber;
		public System.String PartDomain;
		public System.String PartRevision;
		public System.String ReplacePartNumber;
		public System.String ReplacePartDomain;
		public System.String ReplacePartRevision;
		public System.DateTime ReplaceDate;
		public FChoice.Toolkits.Clarify.PartRevisionStatus Status;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdatePartSetupProtocol
	{
		public UpdatePartSetupProtocol(){}

		public System.String PartNumber;
		public System.String PartDomain;
		public System.String Notes;
		public System.String Description;
		public System.String ModelNumber;
		public System.Int32 WarrantyDays;
		public System.Boolean WarrantyStartOnShipment;
		public System.String UnitMeasure;
		public System.String Family;
		public System.String Line;
		public FChoice.Toolkits.Clarify.PartRepairType RepairType;
		public System.String PartType;
		public System.String Weight;
		public System.String Dimension;
		public System.String PartClass;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreatePartSetupProtocol
	{
		public CreatePartSetupProtocol(){}

		public System.String PartNumber;
		public System.String PartDomain;
		public System.String Notes;
		public System.String Description;
		public System.String ModelNumber;
		public System.Int32 WarrantyDays;
		public System.Boolean WarrantyStartOnShipment;
		public System.String UnitMeasure;
		public System.String Family;
		public System.String Line;
		public FChoice.Toolkits.Clarify.PartRepairType RepairType;
		public System.String PartType;
		public System.String Weight;
		public System.String Dimension;
		public System.String PartClass;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddUserToQueueSetupProtocol
	{
		public AddUserToQueueSetupProtocol(){}

		public System.String Queue;
		public System.String UserName;
		public System.Boolean IsSupervisor;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateQueueSetupProtocol
	{
		public CreateQueueSetupProtocol(){}

		public System.String Title;
		public System.Boolean IsPersonal;
		public System.String Description;
		public System.Boolean AllowCR;
		public System.Boolean AllowCase;
		public System.Boolean AllowContract;
		public System.Boolean AllowDialogue;
		public System.Boolean AllowDemandDetail;
		public System.Boolean AllowJob;
		public System.Boolean AllowOpportunity;
		public System.Boolean AllowSolution;
		public System.Boolean AllowSubcase;
		public System.Boolean AllowActionItem;
		public System.String Supervisor;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateQueueSetupProtocol
	{
		public UpdateQueueSetupProtocol(){}

		public System.String Title;
		public System.Boolean IsPersonal;
		public System.String Description;
		public System.Boolean AllowCR;
		public System.Boolean AllowCase;
		public System.Boolean AllowContract;
		public System.Boolean AllowDialogue;
		public System.Boolean AllowDemandDetail;
		public System.Boolean AllowJob;
		public System.Boolean AllowOpportunity;
		public System.Boolean AllowSolution;
		public System.Boolean AllowSubcase;
		public System.Boolean AllowActionItem;
		public System.String Supervisor;
		public System.String NewTitle;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateWipBinSetupProtocol
	{
		public CreateWipBinSetupProtocol(){}

		public System.String Title;
		public System.String Description;
		public System.String UserName;
		public System.Boolean IsDefaultBin;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateWipBinSetupProtocol
	{
		public UpdateWipBinSetupProtocol(){}

		public System.String Title;
		public System.String NewTitle;
		public System.String Description;
		public System.String UserName;
		public System.Boolean IsDefaultBin;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateContactSetupProtocol
	{
		public CreateContactSetupProtocol(){}

		public System.String FirstName;
		public System.String LastName;
		public System.String Phone;
		public System.String SiteIDNum;
		public System.String RoleName;
		public System.String Fax;
		public System.String Email;
		public System.String MailStop;
		public System.String Title;
		public System.String Hours;
		public System.String Salutation;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateContactSetupProtocol
	{
		public UpdateContactSetupProtocol(){}

		public System.String FirstName;
		public System.String LastName;
		public System.String Phone;
		public System.String SiteIDNum;
		public System.String RoleName;
		public System.String Fax;
		public System.String Email;
		public System.String MailStop;
		public System.String Title;
		public System.String Hours;
		public System.String Salutation;
		public System.String NewFirstName;
		public System.String NewLastName;
		public System.String NewPhone;
		public System.String NewPrimarySiteIDNum;
		public System.String NewPrimaryRole;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class RemoveEmployeeFromAccountSetupProtocol
	{
		public RemoveEmployeeFromAccountSetupProtocol(){}

		public System.String UserName;
		public System.String AccountIDNum;
		public System.String RoleName;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddEmployeeToAccountSetupProtocol
	{
		public AddEmployeeToAccountSetupProtocol(){}

		public System.String UserName;
		public System.String AccountIDNum;
		public System.String RoleName;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class RemoveSiteFromAccountSetupProtocol
	{
		public RemoveSiteFromAccountSetupProtocol(){}

		public System.String SiteIDNum;
		public System.String AccountIDNum;
		public System.String RoleName;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddSiteToAccountSetupProtocol
	{
		public AddSiteToAccountSetupProtocol(){}

		public System.String SiteIDNum;
		public System.String AccountIDNum;
		public System.String RoleName;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateAccountSetupProtocol
	{
		public CreateAccountSetupProtocol(){}

		public System.String AccountName;
		public System.String Description;
		public System.String Territory;
		public System.String Stock;
		public System.String FiscalYear;
		public System.String AccountType;
		public System.String Size;
		public System.String Revenue;
		public System.String Ownership;
		public System.String Phone;
		public System.String Fax;
		public System.String WebSite;
		public System.String UserName;
		public System.DateTime CreateDate;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateAccountSetupProtocol
	{
		public UpdateAccountSetupProtocol(){}

		public System.String AccountName;
		public System.String Description;
		public System.String Territory;
		public System.String Stock;
		public System.String FiscalYear;
		public System.String AccountType;
		public System.String Size;
		public System.String Revenue;
		public System.String Ownership;
		public System.String Phone;
		public System.String Fax;
		public System.String WebSite;
		public System.String UserName;
		public System.DateTime CreateDate;
		public System.Boolean GenerateTimeBombs;
		public System.String AccountIDNum;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UnlinkCRFromSolutionSetupProtocol
	{
		public UnlinkCRFromSolutionSetupProtocol(){}

		public System.String CRIDNum;
		public System.String SolutionIDNum;
		public System.DateTime UnlinkDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LinkCRToSolutionSetupProtocol
	{
		public LinkCRToSolutionSetupProtocol(){}

		public System.String CRIDNum;
		public System.String SolutionIDNum;
		public System.DateTime LinkDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UnlinkCaseFromWorkaroundSetupProtocol
	{
		public UnlinkCaseFromWorkaroundSetupProtocol(){}

		public System.String CaseIDNum;
		public System.DateTime UnlinkDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LinkCaseToWorkaroundSetupProtocol
	{
		public LinkCaseToWorkaroundSetupProtocol(){}

		public System.String CaseIDNum;
		public System.Int32 WorkaroundObjid;
		public System.DateTime LinkDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddWorkaroundSetupProtocol
	{
		public AddWorkaroundSetupProtocol(){}

		public System.String SolutionIDNum;
		public System.Int32 SolutionObjid;
		public System.String Workaround;
		public System.Boolean IsPublic;
		public System.DateTime CreateDate;
		public System.String ResolutionCode;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateSolutionSetupProtocol
	{
		public CreateSolutionSetupProtocol(){}

		public System.String Title;
		public System.String Description;
		public System.String Workaround;
		public System.Boolean IsPublic;
		public System.String ResolutionCode;
		public System.String Queue;
		public System.DateTime CreateDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdatePriceInstanceSetupProtocol
	{
		public UpdatePriceInstanceSetupProtocol(){}

		public System.String PartNumber;
		public System.String PartDomain;
		public System.String PartRevision;
		public System.String PriceProgram;
		public System.Int32 PricedQuantity;
		public System.Decimal Price;
		public System.DateTime UpdateDate;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreatePriceInstanceSetupProtocol
	{
		public CreatePriceInstanceSetupProtocol(){}

		public System.String PartNumber;
		public System.String PartDomain;
		public System.String PartRevision;
		public System.String PriceProgram;
		public FChoice.Toolkits.Clarify.PriceInstanceType PriceType;
		public System.Int32 PricedQuantity;
		public System.Decimal Price;
		public System.DateTime StartDate;
		public System.DateTime EndDate;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateBOMSetupProtocol
	{
		public CreateBOMSetupProtocol(){}

		public System.String ParentPartNumber;
		public System.String ParentPartDomain;
		public System.String ParentPartRevision;
		public System.String ChildPartNumber;
		public System.String ChildPartDomain;
		public System.String ChildPartRevision;
		public System.Int32 Quantity;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateSiteSetupProtocol
	{
		public UpdateSiteSetupProtocol(){}

		public System.String SiteIDNum;
		public System.String SiteName;
		public FChoice.Toolkits.Clarify.SiteType SiteType;
		public System.String AccountIDNum;
		public FChoice.Toolkits.Clarify.SiteStatus Status;
		public System.String Region;
		public System.String District;
		public System.String IndustryType;
		public System.String PrimaryUse;
		public System.Int32 PrimaryAddressObjid;
		public System.Int32 ShippingAddressObjid;
		public System.Int32 BillingAddressObjid;
		public System.String ParentSiteIDNum;
		public System.String SupportOfficeSiteIDNum;
		public System.Int32 PrimarySupportEmployeeObjid;
		public System.Int32 SecondarySupportEmployeeObjid;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateSiteSetupProtocol
	{
		public CreateSiteSetupProtocol(){}

		public System.String SiteIDNum;
		public System.String SiteName;
		public FChoice.Toolkits.Clarify.SiteType SiteType;
		public System.String AccountIDNum;
		public FChoice.Toolkits.Clarify.SiteStatus Status;
		public System.String Region;
		public System.String District;
		public System.String IndustryType;
		public System.String PrimaryUse;
		public System.Int32 PrimaryAddressObjid;
		public System.Int32 ShippingAddressObjid;
		public System.Int32 BillingAddressObjid;
		public System.String ParentSiteIDNum;
		public System.String SupportOfficeSiteIDNum;
		public System.Int32 PrimarySupportEmployeeObjid;
		public System.Int32 SecondarySupportEmployeeObjid;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateSiteByObjidSetupProtocol
	{
		public UpdateSiteByObjidSetupProtocol(){}

		public System.Int32 SiteObjid;
		public System.String SiteName;
		public FChoice.Toolkits.Clarify.SiteType SiteType;
		public System.String AccountIDNum;
		public FChoice.Toolkits.Clarify.SiteStatus Status;
		public System.String Region;
		public System.String District;
		public System.String IndustryType;
		public System.String PrimaryUse;
		public System.Int32 PrimaryAddressObjid;
		public System.Int32 ShippingAddressObjid;
		public System.Int32 BillingAddressObjid;
		public System.String ParentSiteIDNum;
		public System.String SupportOfficeSiteIDNum;
		public System.Int32 PrimarySupportEmployeeObjid;
		public System.Int32 SecondarySupportEmployeeObjid;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateTimeZoneSetupProtocol
	{
		public CreateTimeZoneSetupProtocol(){}

		public System.String TimeZone;
		public System.String FullName;
		public System.String Country;
		public System.Int32 GMTDifference;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateStateSetupProtocol
	{
		public CreateStateSetupProtocol(){}

		public System.String State;
		public System.String FullName;
		public System.Boolean IsDefault;
		public System.String Country;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateCountrySetupProtocol
	{
		public CreateCountrySetupProtocol(){}

		public System.String Country;
		public System.Int32 CountryCode;
		public System.String Currency;
		public System.String CurrencySymbol;
		public System.String CurrencyDescription;
		public System.Double CurrencyConversionRate;
		public System.String CurrencyISOCode;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateAddressSetupProtocol
	{
		public UpdateAddressSetupProtocol(){}

		public System.Int32 AddressObjid;
		public System.String Address1;
		public System.String Address2;
		public System.String City;
		public System.String State;
		public System.Boolean IsShortState;
		public System.String ZipCode;
		public System.String Country;
		public System.String TimeZone;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateAddressSetupProtocol
	{
		public CreateAddressSetupProtocol(){}

		public System.String Address1;
		public System.String Address2;
		public System.String City;
		public System.String State;
		public System.Boolean IsShortState;
		public System.String ZipCode;
		public System.String Country;
		public System.String TimeZone;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
}
