//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web;
using System.Web.Services;

using FChoice.Toolkits.Clarify;
using FChoice.WebServices.Clarify;

namespace FChoice.WebServices.Clarify.Protocols.Interfaces
{
	[Serializable]
	public class CreateEmployeeResultProtocol
	{
		public CreateEmployeeResultProtocol(){}
		
		internal CreateEmployeeResultProtocol(FChoice.Toolkits.Clarify.Interfaces.CreateEmployeeResult result)
		{
			this.UserObjid = result.UserObjid;
			this.EmployeeObjid = result.EmployeeObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 UserObjid;
		public System.Int32 EmployeeObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class CreateSolutionResultProtocol
	{
		public CreateSolutionResultProtocol(){}
		
		internal CreateSolutionResultProtocol(FChoice.Toolkits.Clarify.Interfaces.CreateSolutionResult result)
		{
			this.WorkaroundObjid = result.WorkaroundObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 WorkaroundObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
}
