//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web;
using System.Web.Services;

using FChoice.Toolkits.Clarify;
using FChoice.WebServices.Clarify;

namespace FChoice.WebServices.Clarify.Protocols.FieldOps
{
	[Serializable]
	public class PartTransferResultProtocol
	{
		public PartTransferResultProtocol(){}
		
		internal PartTransferResultProtocol(FChoice.Toolkits.Clarify.FieldOps.PartTransferResult result)
		{
			this.TransactionIDNum = result.TransactionIDNum;
			this.StandardCost = result.StandardCost;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.String TransactionIDNum;
		public System.Decimal StandardCost;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class AddServiceInterruptionResultProtocol
	{
		public AddServiceInterruptionResultProtocol(){}
		
		internal AddServiceInterruptionResultProtocol(FChoice.Toolkits.Clarify.FieldOps.AddServiceInterruptionResult result)
		{
			this.ScheduleObjid = result.ScheduleObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 ScheduleObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class CreateExpenseLogResultProtocol
	{
		public CreateExpenseLogResultProtocol(){}
		
		internal CreateExpenseLogResultProtocol(FChoice.Toolkits.Clarify.FieldOps.CreateExpenseLogResult result)
		{
			this.OnsiteLogObjid = result.OnsiteLogObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 OnsiteLogObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class CreateTimeLogResultProtocol
	{
		public CreateTimeLogResultProtocol(){}
		
		internal CreateTimeLogResultProtocol(FChoice.Toolkits.Clarify.FieldOps.CreateTimeLogResult result)
		{
			this.OnsiteLogObjid = result.OnsiteLogObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 OnsiteLogObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
	[Serializable]
	public class CreateAppointmentResultProtocol
	{
		public CreateAppointmentResultProtocol(){}
		
		internal CreateAppointmentResultProtocol(FChoice.Toolkits.Clarify.FieldOps.CreateAppointmentResult result)
		{
			this.ScheduleObjid = result.ScheduleObjid;
			this.ReturnCode = result.ReturnCode;
			this.IDNum = result.IDNum;
			this.Objid = result.Objid;
		}

		public System.Int32 ScheduleObjid;
		public System.Int16 ReturnCode;
		public System.String IDNum;
		public System.Int32 Objid;
		
	}
}
