//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web;
using System.Web.Services;

using FChoice.Toolkits.Clarify;
using FChoice.WebServices.Clarify;

namespace FChoice.WebServices.Clarify.Protocols.Contracts
{
	[Serializable]
	public class UnrelateContractItemFromSitePartSetupProtocol
	{
		public UnrelateContractItemFromSitePartSetupProtocol(){}

		public System.Int32 ContractObjid;
		public System.String PartNumber;
		public System.String PartDomain;
		public System.String PartRevision;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class RelateContractItemToSitePartSetupProtocol
	{
		public RelateContractItemToSitePartSetupProtocol(){}

		public System.Int32 ContractObjid;
		public System.String PartNumber;
		public System.String PartDomain;
		public System.String PartRevision;
		public System.String SerialNumber;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreatePriceInstanceSetupProtocol
	{
		public CreatePriceInstanceSetupProtocol(){}

		public System.String PartNumber;
		public System.String PartRevision;
		public System.String PartDomain;
		public System.String SupportProgram;
		public System.String PriceProgram;
		public FChoice.Toolkits.Clarify.PriceInstanceType PriceType;
		public System.Int32 Quantity;
		public System.Double Price;
		public System.DateTime EffectiveDate;
		public System.DateTime ExpireDate;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AddPOToScheduleSetupProtocol
	{
		public AddPOToScheduleSetupProtocol(){}

		public System.String ContractIDNum;
		public System.String ScheduleIDNum;
		public System.String POIDNum;
		public System.String PaymentOption;
		public System.String PaymentTerms;
		public System.Decimal POAmount;
		public System.DateTime PODate;
		public System.DateTime ExpireDate;
		public System.String POStatus;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateContractLineItemSetupProtocol
	{
		public CreateContractLineItemSetupProtocol(){}

		public System.String ContractIDNum;
		public System.String UserName;
		public System.DateTime CreateDate;
		public System.DateTime StartDate;
		public System.DateTime EndDate;
		public System.String PartNumber;
		public System.String PartDomain;
		public System.String PartRevision;
		public System.Int32 Quantity;
		public System.String PriceSchedule;
		public System.Double OverridePrice;
		public System.Double UnitsUsed;
		public System.String SerialNumber;
		public System.Boolean IsTaxable;
		public System.Boolean AutoInstall;
		public System.String Comments;
		public System.String QuotedSiteIDNum;
		public System.String ServicedAtSiteIDNum;
		public System.Int32 ParentLineItemObjid;
		public System.String POIDNum;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ReopenContractSetupProtocol
	{
		public ReopenContractSetupProtocol(){}

		public System.String ContractIDNum;
		public System.String WipBin;
		public System.String Status;
		public System.DateTime ReopenDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DeleteSitePartSetupProtocol
	{
		public DeleteSitePartSetupProtocol(){}

		public System.Int32 SitePartObjid;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class LogContractNoteSetupProtocol
	{
		public LogContractNoteSetupProtocol(){}

		public System.String ContractIDNum;
		public System.String ActionType;
		public System.String Notes;
		public System.String InternalUseOnlyNotes;
		public System.DateTime LogDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class RejectContractSetupProtocol
	{
		public RejectContractSetupProtocol(){}

		public System.String ContractIDNum;
		public System.String Status;
		public System.String Notes;
		public System.String UserName;
		public System.DateTime RejectDate;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class UpdateScheduleSetupProtocol
	{
		public UpdateScheduleSetupProtocol(){}

		public System.String ContractIDNum;
		public System.String ScheduleIDNum;
		public System.String BillSiteIDNum;
		public System.String BillingATTN;
		public System.String ShipToSiteIDNum;
		public System.String PriceProgram;
		public FChoice.Toolkits.Clarify.BillingFrequency BillingFrequency;
		public FChoice.Toolkits.Clarify.BillingOption BillingOption;
		public System.DateTime BillingPeriodStartDate;
		public System.DateTime FirstBillingDate;
		public System.DateTime ChargeStartDate;
		public System.DateTime ChargeEndDate;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateScheduleSetupProtocol
	{
		public CreateScheduleSetupProtocol(){}

		public System.String ContractIDNum;
		public System.String ScheduleIDNum;
		public System.String BillSiteIDNum;
		public System.String BillingATTN;
		public System.String ShipToSiteIDNum;
		public System.String PriceProgram;
		public FChoice.Toolkits.Clarify.BillingFrequency BillingFrequency;
		public FChoice.Toolkits.Clarify.BillingOption BillingOption;
		public System.DateTime BillingPeriodStartDate;
		public System.DateTime FirstBillingDate;
		public System.DateTime ChargeStartDate;
		public System.DateTime ChargeEndDate;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class YankQuoteSetupProtocol
	{
		public YankQuoteSetupProtocol(){}

		public System.String QuoteIDNum;
		public System.String WipBin;
		public System.DateTime YankDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class RejectQuoteSetupProtocol
	{
		public RejectQuoteSetupProtocol(){}

		public System.String QuoteIDNum;
		public System.DateTime RejectDate;
		public System.String WipBin;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class MoveQuoteSetupProtocol
	{
		public MoveQuoteSetupProtocol(){}

		public System.String QuoteIDNum;
		public System.String NewWipBin;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ForwardQuoteSetupProtocol
	{
		public ForwardQuoteSetupProtocol(){}

		public System.String QuoteIDNum;
		public System.String NewQueue;
		public System.DateTime ForwardDate;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class DispatchQuoteSetupProtocol
	{
		public DispatchQuoteSetupProtocol(){}

		public System.String QuoteIDNum;
		public System.String Queue;
		public System.DateTime DispatchDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class ChangeQuoteStatusSetupProtocol
	{
		public ChangeQuoteStatusSetupProtocol(){}

		public System.String QuoteIDNum;
		public System.String NewStatus;
		public System.DateTime ChangeDate;
		public System.String Notes;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AssignQuoteSetupProtocol
	{
		public AssignQuoteSetupProtocol(){}

		public System.String QuoteIDNum;
		public System.String NewUser;
		public System.String WipBin;
		public System.DateTime AssignDate;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class AcceptQuoteSetupProtocol
	{
		public AcceptQuoteSetupProtocol(){}

		public System.String QuoteIDNum;
		public System.DateTime AcceptDate;
		public System.String WipBin;
		public System.String UserName;
		public System.Boolean GenerateTimeBombs;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
	[Serializable]
	public class CreateContractSetupProtocol
	{
		public CreateContractSetupProtocol(){}

		public System.String ContractIDNum;
		public System.String Title;
		public System.DateTime CreateDate;
		public System.String AccountIDNum;
		public System.String AccountName;
		public System.String ContactFirstName;
		public System.String ContactLastName;
		public System.String ContactPhone;
		public System.String ContractType;
		public System.String Terms;
		public System.String PriceProgram;
		public System.String Status;
		public System.String AdminUserName;
		public System.String BillToSiteIDNum;
		public System.String ShipToSiteIDNum;
		public System.DateTime StartDate;
		public System.DateTime ExpireDate;
		public System.DateTime DefaultStartDate;
		public System.DateTime DefaultExpirationDate;
		public System.String UserName;
		public System.String Queue;
		public System.Boolean IsWarranty;
		public System.Boolean IsEvergreen;
		public System.Int32 RenewPriorDays;
		public System.Boolean GenerateTimeBombs;
		public Protocols.AdditionalFieldProtocol[] AdditionalFields;

		public int DirtyFieldFlags;
		public int ConstructorCue;
		
	}
}
